import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
import ChampionExplorer from "./champion-explorer";
import { championTrees, championSource, nhChampionSource, vtChampionSource, meChampionSource, riChampionSource, stateNames, townKey } from "../../lib/champion-trees";
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "New England Champion Tree Map | Tree Yoga School",
  description: "Explore 624 champion tree records across Massachusetts, New Hampshire, Vermont, Maine, and Rhode Island. Browse an interactive town map, measurements, source records, and tree practices.",
};

export default function ChampionTreesPage() {
  return <><SiteHeader /><main id="content" className="champion-page">
    <section className="champion-intro">
      <Link className="lesson-back" href="/trees">The Tree Library · Out in the world</Link>
      <p className="section-kicker">Five states · Champion Tree Map</p>
      <h1>Meet the giants<br />among us.</h1>
      <p className="lesson-lede">Remarkable trees, rooted in real places. Explore champion trees across Massachusetts, New Hampshire, Vermont, Maine, and Rhode Island, discover their scale, and let curiosity lead you into a deeper relationship with the trees around you.</p>
      <div className="champion-stats"><span><strong>{championTrees.length}</strong> tree records</span><span><strong>{new Set(championTrees.map(townKey)).size}</strong> towns & townships</span><span><strong>{Object.keys(stateNames).length}</strong> states to explore</span></div>
    </section>
    <ChampionExplorer />
    <section className="champion-about" aria-labelledby="about-champions">
      <div><p className="section-kicker">Reading the register</p><h2 id="about-champions">What makes a champion?</h2><p>A champion’s distinction is its size within its species or category; the score does not measure age. DCR’s champion score combines trunk circumference in inches, height in feet, and one quarter of average crown spread in feet.</p><p className="champion-formula">Circumference + height + ¼ crown spread = points</p><p>Measurements and scores appear as published, including zeros and occasional discrepancies. NH’s table labels height and crown spread in feet, but does not specify circumference units. NH detail cards retain those values without assigning units; nomination dates are not measurement dates.</p><p>This map combines Massachusetts’ May 2026 workbook with Maine’s 2020 PDF and the NH and Vermont registers retrieved October 6, 2026. It is a snapshot, not a live register or confirmation of current tree conditions. Only NH entries marked “State” are included. Multiple state-designated records for a species are retained; county-only and historical-status entries are excluded. Vermont includes only records marked as confirmed champions in its official map; multiple confirmed records for a species are retained. Maine includes all 146 entries in the 2020 state register, including multiple entries for some species. Its year of last measurement is shown without inventing a month or day. Rhode Island adds 155 usable rank-one entries from its March 24, 2026 table; one malformed row is excluded and documented below.</p></div>
      <div><p className="section-kicker">A thoughtful visit</p><h2>Let the tree be your teacher.</h2><p>Every marker represents an approximate municipality point, grouping matching records in that town. Massachusetts and Rhode Island publish addresses or sites for many records; NH’s register provides a town and county. Maine’s 2020 register lists towns and townships, without exact tree locations or public-access designations. Vermont publishes coordinates for 24 trees marked publicly accessible. Those cards include a separate link to the published tree position, while map markers remain at town locations. Vermont’s other 67 records are labelled private with no public access. A place name does not establish public access. Check visiting guidance and request permission for private property.</p><p>For NH outings, <a href={nhChampionSource.publicMapUrl} target="_blank" rel="noreferrer">UNH’s public Big Tree Map ↗</a> offers a separate selection of trees on public property or land open to visitors. Its selection includes different champion levels and is not the same as this state-only list.</p><p>You can practice with an ordinary tree nearby, too. Take a few minutes to notice its form, the life around it, and what changes when you give it your attention.</p><Link className="course-link" href="/lessons/first-five-minutes">Your First Five Minutes with a Tree</Link></div>
    </section>
    <section className="champion-sources" aria-label="Map sources"><h2>Sources & map notes</h2>
      <h3>Massachusetts · 139 records</h3><p>The supplied Massachusetts DCR Champion Trees workbook, May 2026. Original names, measurements, location descriptions, and notes are retained. Approximate town centers come from MassGIS municipal polygon centroids retrieved October 6, 2026. “Manchester” is mapped to Manchester-by-the-Sea.</p>
      <div className="course-actions"><a className="course-link" href={championSource.workbookUrl} download>Download the original MA list (.xlsx)</a><a className="course-link" href={championSource.programUrl} target="_blank" rel="noreferrer">DCR Legacy Tree Program ↗</a><a className="course-link" href={championSource.geographyUrl} target="_blank" rel="noreferrer">MassGIS geography ↗</a></div>
      <h3>New Hampshire · 93 state-designated records</h3><p>NH Big Trees’ public register, retrieved October 6, 2026. These records cover 77 scientific-name labels. Original names, measurements, nomination dates, tree IDs, and status designations are preserved. Each detail card links to its source table page; look for the listed Tree ID.</p><p>Approximate NH municipality points come from the U.S. Census Bureau’s 2025 County Subdivisions Gazetteer. East Swanzey uses Swanzey’s point, Rye Beach uses Rye’s, Sanbornville uses Wakefield’s, and “W. Franklin” uses Franklin’s. The source spelling “Boscowen” is interpreted as Boscawen in Merrimack County. Cards retain the original place names and explain these mappings. Points do not locate villages or individual trees.</p>
      <div className="course-actions"><a className="course-link" href={nhChampionSource.registerUrl} target="_blank" rel="noreferrer">NH Big Trees register ↗</a><a className="course-link" href={nhChampionSource.programUrl} target="_blank" rel="noreferrer">NH Big Tree Program ↗</a><a className="course-link" href={nhChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census geography ↗</a></div>
      <h3>Vermont · 91 confirmed champions</h3><p>The official Vermont Big Tree List’s public data view, retrieved October 6, 2026, filtered to confirmed champions. Common and scientific names, measurements, data collection dates, and access labels are retained; excess whitespace is normalized. One record has no common name. Missing names and source discrepancies are identified in the details.</p><p>Vermont’s register marks 24 records publicly accessible and 67 with no public access. Visibility from a road does not grant entry. Only coordinates explicitly published for public trees are linked; private tree coordinates are not included. Town markers use representative points from the Census Bureau’s 2025 County Subdivisions Gazetteer.</p><p>The program’s September 2026 notice says activities are temporarily on hold following a staffing transition. This map preserves the published register as a dated snapshot; check the original program for updates.</p><div className="course-actions"><a className="course-link" href={vtChampionSource.registerUrl} target="_blank" rel="noreferrer">Vermont Big Tree List ↗</a><a className="course-link" href={vtChampionSource.programUrl} target="_blank" rel="noreferrer">Vermont Big Tree Program ↗</a><a className="course-link" href={vtChampionSource.geographyUrl} target="_blank" rel="noreferrer">Vermont Census geography ↗</a></div>
      <h3>Maine · 146 records · 2020 edition</h3><p>The Maine Forest Service’s Register of Big Trees, downloaded October 6, 2026. The official program still links to the 2020 edition. All 146 table entries are retained, including multiple trees of the same species. The PDF’s original spellings, asterisks, measurements, scores, and last-measured years are preserved. The PDF has no asterisk legend, so symbols are not interpreted as verified national or co-champion designations. Published score discrepancies are flagged in record details.</p><p>These records use 65 approximate town and township points. Most come from the Census Bureau’s 2025 County Subdivisions Gazetteer. Bradstreet and Moosehead Junction use Maine GIS township polygon centroids. South Paris is grouped under Paris; “Milton Plantation” uses Milton’s unorganized-territory point; “Bradstreet Twp.” is matched to Bradstreet Twp. Original place names remain on the cards. Counties are added from this official geography, not from the tree register.</p><p>The register does not publish addresses, exact tree coordinates, or access permissions. Maine entries therefore do not appear under “Source confirms public access.” A 2020 listing does not establish a tree’s current condition or champion status.</p><div className="course-actions"><a className="course-link" href={meChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Maine register · 2020 PDF ↗</a><a className="course-link" href={meChampionSource.programUrl} target="_blank" rel="noreferrer">Maine Forest Service Big Trees ↗</a><a className="course-link" href={meChampionSource.geographyUrl} target="_blank" rel="noreferrer">Maine Census geography ↗</a><a className="course-link" href={meChampionSource.townshipUrl} target="_blank" rel="noreferrer">Maine GIS townships ↗</a></div>
      <h3>Rhode Island · 155 records · March 24, 2026 edition</h3><p>The Rhode Island Tree Council’s Helen Walker Raleigh Champion Trees Program register, retrieved October 6, 2026. All 155 usable entries marked rank 1 are included, including multiple entries for a species. Names, addresses, measurements, and published scores are preserved with whitespace normalized. The page’s older gallery count differs from the dated table used here. Measurement dates are not provided.</p><p>The table’s final Zelkova row contains numbers in the species, common-name, town, and address columns. That malformed row is excluded until its identity and location can be confirmed. No replacement record is invented.</p><p>The 28 municipality points and county names come from the Census Bureau’s 2025 County Subdivisions Gazetteer. One empress-tree entry places “Swan Point Cemetery” in the city/town column; its original fields are retained and it is grouped under Providence, where <a href={riChampionSource.cemeteryUrl} target="_blank" rel="noreferrer">the cemetery’s own website ↗</a> locates it. Published addresses do not establish visiting permission; Rhode Island entries are unclassified for public access.</p><div className="course-actions"><a className="course-link" href={riChampionSource.registerUrl} target="_blank" rel="noreferrer">Rhode Island champion register ↗</a><a className="course-link" href={riChampionSource.geographyUrl} target="_blank" rel="noreferrer">Rhode Island Census geography ↗</a></div>
      <p>Map tiles: © OpenStreetMap contributors. Tree Yoga School created this independent exploration of the five registers.</p>
    </section>
  </main><SiteFooter /></>;
}
