import { pageMetadata } from "../../lib/site-seo";
import { Suspense } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
import ChampionExplorer from "./champion-explorer";
import { championSource, mnChampionSource, wiChampionSource, ohChampionSource, miChampionSource, ilChampionSource, flChampionSource, alChampionSource, inChampionSource, kyChampionSource, gaChampionSource, tnChampionSource, scChampionSource, ncChampionSource, wvChampionSource, vaChampionSource, nhChampionSource, vtChampionSource, meChampionSource, riChampionSource, ctChampionSource, nyChampionSource, njChampionSource, paChampionSource, deChampionSource, mdChampionSource, stateNames, sourceDates } from "../../lib/champion-trees";
import "leaflet/dist/leaflet.css";
import { championTrees, championManifest } from "../../lib/champion-tree-data";
import { treeVisitSummary } from "../../lib/tree-visits";

const pageInfo: Metadata = {
  title: "Champion Tree Map | Tree Yoga School",
  description: `Explore ${championTrees.length.toLocaleString("en-US")} champion and score-based leader records across Massachusetts, New Hampshire, Vermont, Maine, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, Maryland, Virginia, West Virginia, North Carolina, South Carolina, Tennessee, Georgia, Kentucky, Indiana, Alabama, Florida, Illinois, Michigan, Ohio, Wisconsin, Minnesota, Iowa, Missouri, Arkansas, Kansas, Nebraska, Texas, Colorado, Louisiana, and Oklahoma. Browse an interactive town, county, and parish map, measurements, source records, and tree practices. Ohio includes the complete 127-entry native and 126-entry non-native lists.`,
};
export const metadata: Metadata = pageMetadata("/champion-trees", String(pageInfo.title), String(pageInfo.description));

export default function ChampionTreesPage() {
  return <><SiteHeader /><main id="content" className="champion-page">
    <section className="champion-intro">
      <Link className="lesson-back" href="/trees">The Tree Library · Out in the world</Link>
      <p className="section-kicker">{Object.keys(stateNames).length} states to explore · Champion Tree Map</p>
      <h1>Meet the giants<br />among us.</h1>
      <p className="lesson-lede">Remarkable trees, rooted in real places. Explore published champion and score-based leader records across {Object.keys(stateNames).length} states. Choose a state, find a species, and discover the scale of the trees around you.</p>
      <div className="champion-stats"><span><strong>{championTrees.length.toLocaleString("en-US")}</strong> listed trees</span><span><strong>{championManifest.reduce((total, state) => total + state.mapped, 0).toLocaleString("en-US")}</strong> mapped trees</span><span><strong>{Object.keys(stateNames).length}</strong> states to explore</span></div>
      <nav className="champion-page-links" aria-label="On the Champion Map page"><a className="button primary" href="#explorer">Explore the map ↓</a><a className="course-link" href="#registers">State registers & sources ↓</a></nav>
    </section>
    <Suspense fallback={<p role="status">Opening the champion tree explorer…</p>}><ChampionExplorer manifest={championManifest} /></Suspense>
    <aside className="tree-visit-teaser"><h2>Looking for a tree to visit?</h2><p>{treeVisitSummary}</p><Link className="course-link" href="/tree-visits">Explore trees to visit →</Link></aside>
    <section className="champion-source-dates" id="registers" aria-label="State register dates"><p className="section-kicker">The registers behind the map</p><h2>Which lists are we exploring?</h2><p>Choose a state below for its source notes, register date, and original links.</p><a className="course-link" href="#explorer">Return to the explorer ↑</a><div className="champion-date-grid">{championManifest.map(s => <a key={s.state} href={`#source-${s.state}`}><strong>{s.name}</strong><span>{sourceDates[s.state]}</span><small>{s.listed.toLocaleString("en-US")} listed · {s.mapped.toLocaleString("en-US")} mapped</small></a>)}</div><p className="champion-location-note">Mapped means an approximate town, Census place, or county point is available, not an exact tree location. Retrieval dates describe our snapshot, not when a tree was measured.</p></section>
    <section className="lesson-section" id="source-OK"><p className="section-kicker">Oklahoma · Forestry Services champion map</p><h2>Great trees of the plains and forests.</h2><p>79 source-designated champions from the Oklahoma Forestry Services interactive map, retrieved October 10, 2026. Its dataset was updated June 10, 2026; that update date does not mean every tree was recently measured. Of 213 source records, 83 are marked as champions, 22 as non-champions, and 108 as undefined. Four champion records with reported deaths—Weeping Willow, Lacebark Elm, Black Hickory, and Pecan—are excluded.</p><p>Both River Birch champions remain separate records. Names, measurements, and scores are preserved as supplied, including spelling inconsistencies and four missing scores. Only the explicit Date Measured field is used for measurement dates; the separate Year field is shown without interpreting it as a measurement date.</p><p>All 79 records use 27 approximate Census county points. These markers do not locate individual trees or establish permission to visit. Public-access classifications are shown where supplied, while addresses, landowner contact details, and individual tree coordinates are omitted. Current conditions have not been independently verified.</p><p><a href="https://storymaps.arcgis.com/stories/05009ef918c34590b5ba5d9fb4ec6334" target="_blank" rel="noreferrer">Oklahoma Forestry Services interactive register ↗</a> · <a href="https://ag.ok.gov/championtrees/" target="_blank" rel="noreferrer">Official program and historical 2014 PDF ↗</a></p></section>
    <section className="lesson-section" id="source-LA"><p className="section-kicker">Louisiana · older published register</p><h2>Giants of the bayous and parishes.</h2><p>115 records from all six pages of the Louisiana Forestry Association’s online table, retrieved October 10, 2026. The page displays “2021 listing”; its precise edition is unconfirmed, and champions announced in 2025 and 2026 are missing. This is an older published snapshot, not a verified current register.</p><p>All 37 source-designated co-champions remain separate records, regardless of their scores. The East Feliciana Winged Elm is excluded because the source reports it deceased. The deceased Sassafras is already absent from the table. The historical national-champion flag is preserved without confirming current national status.</p><p>All records use 34 approximate Census parish points. These markers do not locate individual trees or establish permission to visit. Scientific names and measurement dates are not supplied. Original measurement text is retained in each record’s notes; circumference is converted to inches, and height and spread to feet. The Tallowtree’s spread punctuation conflicts with its score and is explained on its card. Published scores remain unchanged.</p><p><a href="https://www.laforestry.com/champion-trees-in-louisiana" target="_blank" rel="noreferrer">Louisiana Forestry Association register ↗</a> · <a href="https://www.laforestry.com/single-post/new-red-maple-champion-in-caldwell" target="_blank" rel="noreferrer">2025 champion additions ↗</a> · <a href="https://www.laforestry.com/single-post/toothache-tree-added-to-champion-tree-list" target="_blank" rel="noreferrer">2026 Hercules Club announcement ↗</a></p></section>
    <section className="lesson-section" id="source-CO"><p className="section-kicker">Colorado · 2026 register</p><h2>Published positions. Remarkable trees.</h2><p>All 846 records from the Colorado Tree Coalition’s 2026 county and alphabetical workbooks are included. Both lists reconcile across names, measurements, scores, positions, and general locations, with one cultivar-name difference: Hot Wings in the county list and GarAnn Hot Wings in the alphabetical list. The difference is noted on its record.</p><p>The register includes 354 position-1 or 1T listings, other positions through 7, and one entry without a position, height, or points. We preserve every published position and T suffix rather than calculating titles or reducing the list to three trees per species. The “Nat’l Pts.” column gives points; it does not establish national champion status.</p><p>All records map to 45 approximate Census county points. The source’s Moffatt spelling maps to Moffat County. One street address is omitted, and no individual-tree coordinates or visiting permission are inferred. Dates of measurement are not supplied. Circumference and diameter are in inches; height and average crown spread are in feet. Source spellings, varieties, missing values, and published scores remain intact.</p><div className="course-actions"><a className="course-link" href="https://www.coloradotrees.org/colorado-champion-trees" target="_blank" rel="noreferrer">Colorado Tree Coalition register ↗</a><a className="course-link" href="https://www.coloradotrees.org/s/2026-Website-County-champ-list.xlsx" target="_blank" rel="noreferrer">2026 county workbook ↗</a><a className="course-link" href="https://www.coloradotrees.org/s/2026-Website-Champ-Trees.xlsx" target="_blank" rel="noreferrer">2026 alphabetical workbook ↗</a><a className="course-link" href="https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer/2025_Gaz_counties_national.zip" target="_blank" rel="noreferrer">Census county geography ↗</a></div></section>

    <section className="champion-about" aria-labelledby="source-TX"><div><h3 id="source-TX">Texas · 232 unique champion records</h3><p>Texas A&M Forest Service’s live Big Tree Registry, retrieved October 9, 2026. The 661-record registry lists 229 state champions and 54 national champions; 51 trees appear in both categories. We include their union of 232 unique Tree IDs, including state and national co-champions. The other 429 registry records are not imported. Titles are source designations, not independently verified current national titles.</p><p>All 232 records map to 79 approximate 2025 Census county points. Ownership labels identify 152 private records, 72 public records, and eight unclassified records. Public ownership is not a guarantee of visiting access. Private owner names and all exact tree coordinates are omitted. Consult the official registry and landowner before visiting.</p><p>Circumference is in inches; height and spread are in feet. Tree Index values remain as published without recalculation. Measurement, nomination and certification dates retain the source’s month/year precision. Certification and historical condition labels do not confirm current tree condition.</p></div><div><a className="button secondary" href="https://texasforestinfo.tamu.edu/BigTreeRegistry/Lists" target="_blank" rel="noreferrer">Official Texas champion lists ↗</a><p className="source-note"><a href="https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer/2025_Gaz_counties_national.zip" target="_blank" rel="noreferrer">Census 2025 counties ↗</a> · approximate geography</p></div></section>
    <section className="champion-about" aria-labelledby="source-NE"><div><h3 id="source-NE">Nebraska · 90 champion register records</h3><p>Nebraska Forest Service at the University of Nebraska–Lincoln, retrieved October 9, 2026. All 90 published rows are included, including numbered and repeated species entries. Names and scores remain as published; co-champion titles are not inferred. Nomination and measurement dates remain separate, and year-only dates retain their original precision. No edition date is stated.</p><p>83 records use 42 approximate 2025 Census place points. Seven remain searchable without markers: Sparks and Marsland do not match Census place names, and five records do not name an unambiguous municipality. Nearby and directional descriptions refer only to the named place, not the tree. Counties and visiting permission are not inferred. Consult the register and landowner before visiting.</p><p>Circumference in feet is converted to inches. Peachleaf Willow’s explicit 124-inch circumference takes precedence over the feet column heading. Published scores remain unchanged, including inconsistencies with measurements. Published location descriptions are retained, but personal steward names and exact tree coordinates are not copied.</p></div><div><a className="button secondary" href="https://nfs.unl.edu/registry/" target="_blank" rel="noreferrer">Official Nebraska register ↗</a><p className="source-note"><a href="https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer/2025_gaz_place_31.txt" target="_blank" rel="noreferrer">Census 2025 Nebraska places ↗</a> · approximate geography</p></div></section>
    <section className="champion-about" aria-labelledby="source-KS"><div><h3 id="source-KS">Kansas · 148 champion register records</h3><p>Kansas Forest Service at Kansas State University, retrieved October 9, 2026. All 148 rows are included, including four explicitly labeled co-champions and repeated species with unequal scores. Names and scores remain as published, including spelling inconsistencies. Nomination years and last-measured dates are separate; the page does not state an edition date.</p><p>134 records match 60 approximate 2025 Census place points. Fourteen records in Fort Leavenworth, Sequin, Stilwell, Studley, Waterloo, and Willowdale do not exactly match Census place names and remain searchable without a marker. Counties are not supplied or inferred. Markers do not locate individual trees, and public visiting access is unclassified.</p><p>Circumference is in inches and height in feet. Crown spread is interpreted in feet, consistent with the published scoring convention; published scores are retained even when they differ from the listed measurements. No private addresses, nominator names, or tree coordinates are imported.</p></div><div><a className="button secondary" href="https://www.kansasforests.org/programs/championtreelist.html" target="_blank" rel="noreferrer">Official Kansas register ↗</a><p className="source-note"><a href="https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2025_Gazetteer/2025_gaz_place_20.txt" target="_blank" rel="noreferrer">Census 2025 Kansas places ↗</a> · approximate geography</p></div></section>
    <section className="champion-about" aria-labelledby="source-AR"><div><h3 id="source-AR">Arkansas · 125 champion register records</h3><p>Arkansas Department of Agriculture’s Forestry Division register, retrieved October 9, 2026. All nine pages are included: 15 records on each of pages 1–8 and five on page 9. Measurements were checked on all 125 detail pages. Co-champions, tri-champions and repeated species remain separate, including entries with unequal published scores. Vacant species are not tree records.</p><p>124 records use 50 approximate Census county points. Eastern Cottonwood has no published county and remains searchable without a marker. Source property labels distinguish public, limited public access, private property, street viewing and private property with access allowed. Seven records have no access classification. County markers do not locate the trees; confirm current visiting arrangements with the site or Forestry Division.</p><p>Circumference is shown in inches; height and crown spread in feet. Four circumference fields have foot marks and one crown field has an inch mark that conflict with the program formula. Their values are interpreted using the program’s units because those units agree with published scores within rounding, with the original text retained in individual source notes. Published scores remain unchanged. Missing names are resolved from detail-page titles, with notes. No measurement dates or confirmed list edition are supplied.</p><p><a href="https://agriculture.arkansas.gov/forests/urban-community-forestry/champion-trees/search-champion-trees/" target="_blank" rel="noreferrer">Official Arkansas Champion Tree register ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="source-MO"><div><h3 id="source-MO">Missouri · 151 Champion Tree Register records</h3><p>Missouri Department of Conservation’s official GIS register, retrieved October 9, 2026. All 151 records are included, with source names, measurements and published scores preserved. MDC describes the register as including trees that are, or were, qualified champions. Current titles and tree conditions are unconfirmed.</p><p>All records use 59 approximate Census county or independent-city points. MDC lists public access for 51 records and no public access for 100. Public site names appear where access is listed; personal owner names, private locations and exact tree coordinates are excluded. St. Louis City and St. Louis County remain separate.</p><p>Circumference is shown in inches; height and crown spread in feet, following MDC’s measuring guidance. Published scores are retained even where they differ from calculated totals. Measurement dates and the latest record-update year are not supplied. The service metadata was created December 2, 2021; this is not a confirmed list edition.</p><p><a href="https://gisblue.mdc.mo.gov/arcgis/rest/services/Land_Cover/Champion_Trees_List/MapServer/0" target="_blank" rel="noreferrer">Official Missouri Champion Trees dataset ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="source-IA"><div><h3 id="source-IA">Iowa · 67 official champion map records</h3><p>Iowa DNR’s current Big Tree Viewer, retrieved October 9, 2026. Its active map layer contains 159 records; we include the 67 whose status is explicitly rendered as “Champion Tree.” Status 2 and 3 are runners-up. We do not merge the separate older spreadsheet or derive additional champions from scores.</p><p>66 records use 36 approximate Census county points. One record has no published county and remains searchable without a marker. Private ownership is labelled private; other ownership does not establish visiting permission. Exact tree coordinates, addresses, directions, and personal contact details are not included.</p><p>The official web map labels circumference in feet despite a service field name that says inches. We convert those values to inches and preserve the original text in record notes. Height and crown spread are in feet. Explicit crown averages and published scores are retained even when inconsistent; crown diameter pairs without an explicit average remain text with an unknown numeric average. Last-update dates are shown separately from unconfirmed measurement dates. The map layer reports data last edited July 9, 2026.</p><p><a href="https://experience.arcgis.com/experience/db8a533a6ca34fc89a3df0603b6b2cb4/" target="_blank" rel="noreferrer">Official Iowa Big Tree Viewer ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="source-MN"><div><h3 id="source-MN">Minnesota · 62 current champion records</h3><p>Minnesota DNR’s current Big Tree Champions page, retrieved {mnChampionSource.retrieved}. All 62 listed trees across 51 native species are included. Northern mountain ash and Mountain maple have empty species slots and are excluded. Multiple trees within a species are shown as co-champions by DNR’s page; every listed tree is retained.</p><p>All 62 trees use 28 approximate Census county points. Published location descriptions and ownership remain in the records; these markers do not locate individual trees. The 24 private-ownership records are labelled private. Public, Federal, or Tribal ownership does not establish visiting permission.</p><p>Circumference is in inches; height and crown spread are in feet. Total points follow DNR’s displayed calculation: circumference + height + one-quarter crown spread. The source year appears beside the nominator and is shown separately from unknown measurement dates. National champion flags are DNR’s labels, without independent confirmation. St Louis and St.Louis are normalized to St. Louis; Fairibault is matched to Faribault, with original county spellings preserved.</p><p><a href={mnChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Minnesota champions ↗</a> · <a href={mnChampionSource.measuringUrl} target="_blank" rel="noreferrer">DNR measurement and co-champion rules ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="source-WI"><div><h3 id="source-WI">Wisconsin · 57 official champion map records</h3><p>Wisconsin DNR’s official Champion Tree map and data table, retrieved {wiChampionSource.retrieved}. All 47 records in the exact-location layer and all 10 township-display records are included using the official map filters. Repeated species remain separate; no additional champions are derived from points.</p><p>All 57 records use 21 approximate Census county points. These markers do not locate individual trees. DNR shares exact locations for some trees, including trees on private property; location sharing does not establish visiting permission. The 28 private-property records are labelled private; the other 29 have unclassified visiting access. Consult the official map for its published location information.</p><p>Circumference is in inches; height and crown width are in feet. Average crown width follows the official map’s average of its two verified crown diameters; both diameters remain in record notes. Published scores are retained. Measurement dates are not supplied. The exact-location layer reports data last edited September 7, 2026; the township layer February 9, 2023. DNR currently reports a staffing-related pause and cannot respond to nominations or program information requests.</p><p><a href={wiChampionSource.registerUrl} target="_blank" rel="noreferrer">Official data table ↗</a> · <a href={wiChampionSource.mapUrl} target="_blank" rel="noreferrer">Official Wisconsin map ↗</a> · <a href={wiChampionSource.programUrl} target="_blank" rel="noreferrer">Wisconsin DNR program ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="source-OH"><div><h3 id="source-OH">Ohio · complete native and non-native lists</h3><p>All {ohChampionSource.nativeCount} entries from the Native Ohio Champion Trees list are included, checked against all six table pages (1–127 of 127) in screenshots captured {ohChampionSource.captured}. All {ohChampionSource.nonNativeCount} non-native entries are also included, checked against all six non-native pages (1–126 of 126).</p><p>Names, circumference in inches, height and crown spread in feet, scores, and counties follow the published tables. Separate rows are retained even when species repeat, including both Black Ash trees, both Pawpaw trees, both Scarlet Oaks, and both entries for Crataegus coccinea var. pringlei. The non-native table also repeats Common Apple, Hedge Maple, and Western Red Cedar; every row remains included. The two Western Red Cedar rows have identical measurements and county and may refer to the same tree. Membership in the native or non-native list follows the source table.</p><p>{ohChampionSource.mappedCount} records use {ohChampionSource.countyCount} approximate Census county points. Gray Birch has no county in the source and remains searchable without a marker. Measurement dates, exact tree locations, and visiting access are not supplied. American elm retains the published 333 points despite a discrepancy with its measurements.</p><p><a href={ohChampionSource.nativeUrl} target="_blank" rel="noreferrer">Official native champion list ↗</a> · <a href={ohChampionSource.nonNativeUrl} target="_blank" rel="noreferrer">Official non-native champion list ↗</a></p></div></section>
    <section className="champion-about" aria-labelledby="about-champions">
      <div><p className="section-kicker">Reading the register</p><h2 id="about-champions">What makes a champion?</h2><p>A champion’s distinction is its size within its species or category; the score does not measure age. DCR’s champion score combines trunk circumference in inches, height in feet, and one quarter of average crown spread in feet.</p><p className="champion-formula">Circumference + height + ¼ crown spread = points</p><p>Measurements and scores appear as published, including zeros and occasional discrepancies. NH’s table labels height and crown spread in feet, but does not specify circumference units. NH detail cards retain those values without assigning units; nomination dates are not measurement dates.</p><p>This map combines Massachusetts’ May 2026 workbook with Maine’s 2020 PDF and the NH and Vermont registers retrieved October 6, 2026. It is a snapshot, not a live register or confirmation of current tree conditions. Only NH entries marked “State” are included. Multiple state-designated records for a species are retained; county-only and historical-status entries are excluded. Vermont includes only records marked as confirmed champions in its official map; multiple confirmed records for a species are retained. Maine includes all 146 entries in the 2020 state register, including multiple entries for some species. Its year of last measurement is shown without inventing a month or day. Rhode Island adds 155 usable rank-one entries from its March 24, 2026 table; one malformed row is excluded and documented below. Connecticut includes 400 champions and 104 co-champions explicitly designated in its champion lists; other notable and historic trees are excluded. New York adds 210 champions and co-champions from its January 31, 2025 register. New Jersey adds 206 records explicitly designated Champion, Co-Champion, Heritage Champion, or National Champion by NJDEP. Pennsylvania adds 445 score-based leaders from PA Big Trees, with qualifications for ties, legacy flags, and incomplete detail checks. Delaware adds 79 rank-one records and 12 additional qualifiers under its published five-point co-champion rule, using the current FirstMap dataset. Maryland adds 274 entries explicitly marked State in its current champion table, retaining multiple designated trees in a botanical category. Virginia adds 369 entries from Virginia Tech’s current state champion list, checked against the individual tree records. West Virginia adds 159 highest-scoring entries from its 2025 workbooks, retaining exact ties and excluding a category with conflicting species names. North Carolina adds 346 current champions and co-champions from its September 2026 roster.</p></div>
      <div><p className="section-kicker">A thoughtful visit</p><h2>Let the tree be your teacher.</h2><p>Oklahoma, Florida, Alabama, Illinois, Indiana, Michigan, Ohio, Wisconsin, Minnesota, Kentucky, Georgia, Tennessee, South Carolina, North Carolina, West Virginia, Virginia, Maryland, New York, Pennsylvania, and some New Jersey and Delaware records use approximate county points; other markers use town or Census place points. New York’s register supplies counties only. Massachusetts, Rhode Island, and Connecticut publish addresses or sites for some records; NH’s register provides a town and county. Maine’s 2020 register lists towns and townships, without exact tree locations or public-access designations. Vermont publishes coordinates for 24 trees marked publicly accessible. Those cards include a separate link to the published tree position, while map markers remain at town locations. Vermont’s other 67 records are labelled private with no public access. A place name does not establish public access. Check visiting guidance and request permission for private property.</p><p>For NH outings, <a href={nhChampionSource.publicMapUrl} target="_blank" rel="noreferrer">UNH’s public Big Tree Map ↗</a> offers a separate selection of trees on public property or land open to visitors. Its selection includes different champion levels and is not the same as this state-only list.</p><p>You can practice with an ordinary tree nearby, too. Take a few minutes to notice its form, the life around it, and what changes when you give it your attention.</p><Link className="course-link" href="/lessons/first-five-minutes">Your First Five Minutes with a Tree</Link></div>
    </section>
    <section className="champion-sources" aria-label="Map sources"><h2>Sources & map notes</h2>
      <h3 id="source-MA">Massachusetts · 139 records</h3><p>The supplied Massachusetts DCR Champion Trees workbook, May 2026. Original names, measurements, location descriptions, and notes are retained. Approximate town centers come from MassGIS municipal polygon centroids retrieved October 6, 2026. “Manchester” is mapped to Manchester-by-the-Sea.</p>
      <div className="course-actions"><a className="course-link" href={championSource.workbookUrl} download>Download the original MA list (.xlsx)</a><a className="course-link" href={championSource.programUrl} target="_blank" rel="noreferrer">DCR Legacy Tree Program ↗</a><a className="course-link" href={championSource.geographyUrl} target="_blank" rel="noreferrer">MassGIS geography ↗</a></div>
      <h3 id="source-NH">New Hampshire · 93 state-designated records</h3><p>NH Big Trees’ public register, retrieved October 6, 2026. These records cover 77 scientific-name labels. Original names, measurements, nomination dates, tree IDs, and status designations are preserved. Each detail card links to its source table page; look for the listed Tree ID.</p><p>Approximate NH municipality points come from the U.S. Census Bureau’s 2025 County Subdivisions Gazetteer. East Swanzey uses Swanzey’s point, Rye Beach uses Rye’s, Sanbornville uses Wakefield’s, and “W. Franklin” uses Franklin’s. The source spelling “Boscowen” is interpreted as Boscawen in Merrimack County. Cards retain the original place names and explain these mappings. Points do not locate villages or individual trees.</p>
      <div className="course-actions"><a className="course-link" href={nhChampionSource.registerUrl} target="_blank" rel="noreferrer">NH Big Trees register ↗</a><a className="course-link" href={nhChampionSource.programUrl} target="_blank" rel="noreferrer">NH Big Tree Program ↗</a><a className="course-link" href={nhChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census geography ↗</a></div>
      <h3 id="source-VT">Vermont · 91 confirmed champions</h3><p>The official Vermont Big Tree List’s public data view, retrieved October 6, 2026, filtered to confirmed champions. Common and scientific names, measurements, data collection dates, and access labels are retained; excess whitespace is normalized. One record has no common name. Missing names and source discrepancies are identified in the details.</p><p>Vermont’s register marks 24 records publicly accessible and 67 with no public access. Visibility from a road does not grant entry. Only coordinates explicitly published for public trees are linked; private tree coordinates are not included. Town markers use representative points from the Census Bureau’s 2025 County Subdivisions Gazetteer.</p><p>The program’s September 2026 notice says activities are temporarily on hold following a staffing transition. This map preserves the published register as a dated snapshot; check the original program for updates.</p><div className="course-actions"><a className="course-link" href={vtChampionSource.registerUrl} target="_blank" rel="noreferrer">Vermont Big Tree List ↗</a><a className="course-link" href={vtChampionSource.programUrl} target="_blank" rel="noreferrer">Vermont Big Tree Program ↗</a><a className="course-link" href={vtChampionSource.geographyUrl} target="_blank" rel="noreferrer">Vermont Census geography ↗</a></div>
      <h3 id="source-ME">Maine · 146 records · 2020 edition</h3><p>The Maine Forest Service’s Register of Big Trees, downloaded October 6, 2026. The official program still links to the 2020 edition. All 146 table entries are retained, including multiple trees of the same species. The PDF’s original spellings, asterisks, measurements, scores, and last-measured years are preserved. The PDF has no asterisk legend, so symbols are not interpreted as verified national or co-champion designations. Published score discrepancies are flagged in record details.</p><p>These records use 65 approximate town and township points. Most come from the Census Bureau’s 2025 County Subdivisions Gazetteer. Bradstreet and Moosehead Junction use Maine GIS township polygon centroids. South Paris is grouped under Paris; “Milton Plantation” uses Milton’s unorganized-territory point; “Bradstreet Twp.” is matched to Bradstreet Twp. Original place names remain on the cards. Counties are added from this official geography, not from the tree register.</p><p>The register does not publish addresses, exact tree coordinates, or access permissions. Maine entries therefore do not appear under “Source confirms public access.” A 2020 listing does not establish a tree’s current condition or champion status.</p><div className="course-actions"><a className="course-link" href={meChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Maine register · 2020 PDF ↗</a><a className="course-link" href={meChampionSource.programUrl} target="_blank" rel="noreferrer">Maine Forest Service Big Trees ↗</a><a className="course-link" href={meChampionSource.geographyUrl} target="_blank" rel="noreferrer">Maine Census geography ↗</a><a className="course-link" href={meChampionSource.townshipUrl} target="_blank" rel="noreferrer">Maine GIS townships ↗</a></div>
      <h3 id="source-RI">Rhode Island · 155 records · March 24, 2026 edition</h3><p>The Rhode Island Tree Council’s Helen Walker Raleigh Champion Trees Program register, retrieved October 6, 2026. All 155 usable entries marked rank 1 are included, including multiple entries for a species. Names, addresses, measurements, and published scores are preserved with whitespace normalized. The page’s older gallery count differs from the dated table used here. Measurement dates are not provided.</p><p>The table’s final Zelkova row contains numbers in the species, common-name, town, and address columns. That malformed row is excluded until its identity and location can be confirmed. No replacement record is invented.</p><p>The 28 municipality points and county names come from the Census Bureau’s 2025 County Subdivisions Gazetteer. One empress-tree entry places “Swan Point Cemetery” in the city/town column; its original fields are retained and it is grouped under Providence, where <a href={riChampionSource.cemeteryUrl} target="_blank" rel="noreferrer">the cemetery’s own website ↗</a> locates it. Published addresses do not establish visiting permission; Rhode Island entries are unclassified for public access.</p><div className="course-actions"><a className="course-link" href={riChampionSource.registerUrl} target="_blank" rel="noreferrer">Rhode Island champion register ↗</a><a className="course-link" href={riChampionSource.geographyUrl} target="_blank" rel="noreferrer">Rhode Island Census geography ↗</a></div>
      <h3 id="source-CT">Connecticut · 504 champions and co-champions</h3><p>Connecticut’s Notable Trees, hosted by Connecticut College and supported by the Connecticut College Arboretum, Connecticut Botanical Society, and Connecticut Urban Forest Council. Retrieved October 6, 2026. The common-name and scientific-name champion lists are matched by Tree ID and checked against individual records. Only explicit Connecticut champion and co-champion designations are included: 400 champions and 104 co-champions. The register includes species, hybrids, and cultivated varieties; multiple designated trees remain separate.</p><p>Original names, measurements, points, measurement dates, named-tree labels, and published addresses are retained with whitespace normalized. Cards use the individual record’s common name; alternate names from the alphabetized list appear in searchable source notes. Each card links to its original record for photographs, directions, and additional context. Published locations do not establish public access, and no access permission is inferred. Locations withheld by the program remain undisclosed. Map markers are approximate municipality points.</p><p>The 97 Connecticut town points come from the Census Bureau’s 2025 County Subdivisions Gazetteer. The county filter is expanded to “County or planning region” because current Census geography uses Connecticut’s nine planning regions as county equivalents. These region names are added from Census geography, not from the tree register.</p><div className="course-actions"><a className="course-link" href={ctChampionSource.registerUrl} target="_blank" rel="noreferrer">Connecticut champions by common name ↗</a><a className="course-link" href={ctChampionSource.scientificUrl} target="_blank" rel="noreferrer">Connecticut champions by scientific name ↗</a><a className="course-link" href={ctChampionSource.geographyUrl} target="_blank" rel="noreferrer">Connecticut Census geography ↗</a><a className="course-link" href={ctChampionSource.regionsUrl} target="_blank" rel="noreferrer">Connecticut planning regions ↗</a></div>
      <h3 id="source-NY">New York · 210 champions and co-champions · January 31, 2025</h3><p>NYS DEC’s Big Tree Register, retrieved October 6, 2026. The scientific-name and common-name PDFs contain the same 210 records: 162 champions and 48 co-champions. Asterisks identify co-champions. The lists are reconciled across all measurements, counties, regions, nominators, and years; two scientific names are clipped differently between layouts, noted on their cards. Published measurements, names, and scores are retained.</p><p>The register gives counties without towns, addresses, tree coordinates, or access permissions. All 210 records use 37 approximate county points from the Census Bureau’s 2025 Counties Gazetteer. County markers do not identify the tree’s location. “Montgomer,” “St. Lawrenc,” “Cattaragus,” and “Wyomng” are matched to Montgomery, St. Lawrence, Cattaraugus, and Wyoming; original wording remains in source notes. No visiting permission is inferred.</p><p>New York publishes crown points, equal to one quarter of average crown spread in feet. Cards show that original contribution explicitly rather than labeling it as full crown spread. Last-measured years remain distinct from the register’s edition date.</p><div className="course-actions"><a className="course-link" href={nyChampionSource.registerUrl} target="_blank" rel="noreferrer">New York register · scientific names ↗</a><a className="course-link" href={nyChampionSource.commonUrl} target="_blank" rel="noreferrer">New York register · common names ↗</a><a className="course-link" href={nyChampionSource.programUrl} target="_blank" rel="noreferrer">NYS DEC Big Tree Program ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-NJ">New Jersey · 206 champion-designated records</h3><p>The New Jersey Forest Service’s official NJDEP Big and Heritage Trees public dataset, retrieved October 6, 2026. The dataset reports a last edit of March 19, 2026; individual measurement dates are not supplied. We include only records with permission to list marked YES and an explicit champion status: 182 Champion, 9 Co-Champion, 8 Heritage Champion, and 7 National Champion. National designations are shown as NJDEP’s labels, without independently asserting current national status. Published rankings are retained even where they differ from first place; inclusion follows the official status field.</p><p>All 206 records remain searchable. We map 110 records to 59 unambiguously matched municipalities within their published counties. The other 96 records use 17 clearly labeled county points because the municipality is a village, ambiguous, misspelled, or inconsistent with its county. Original municipality names and published addresses remain in the details. Points come from the Census Bureau’s 2025 Gazetteer; they do not locate individual trees. Tree coordinates are not imported, and permission to list is not treated as permission to visit.</p><p>Botanical-name code underscores are displayed as spaces. Names, measurements, rankings, and status designations otherwise remain as published. NJDEP’s crown field is labeled “Crown Average (in.)” although its scoring guidance uses feet. We display the original crown value without assigning a confirmed unit, converting it, or recalculating the score. This inconsistency is explained on each record.</p><div className="course-actions"><a className="course-link" href={njChampionSource.registerUrl} target="_blank" rel="noreferrer">Official New Jersey map &amp; registry ↗</a><a className="course-link" href={njChampionSource.programUrl} target="_blank" rel="noreferrer">NJDEP Big &amp; Heritage Trees ↗</a><a className="course-link" href={njChampionSource.dataUrl} target="_blank" rel="noreferrer">NJDEP public dataset ↗</a><a className="course-link" href={njChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census municipality geography ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-PA">Pennsylvania · 445 score-based leaders</h3>
      <p>The Pennsylvania Forestry Association’s PA Big Trees register, using the supplied October 2026 extraction. All 1,520 public listing records were compared by source genus and species category, retaining each maximum published score. Source categories include species, hybrids, cultivars, varieties, and forms; their original names are preserved. These are derived state-leader candidates, not an independently certified champion-only roster.</p>
      <p>The extraction identified 446 leaders across 441 named botanical categories. We exclude the <a href="https://pabigtrees.com/morris-arboretum-100-e-northwestern-ave-phila-tr20100930204444730" target="_blank" rel="noreferrer">Northern Pin Oak marked “removed” ↗</a>, leaving 445 records across 440 categories. No successor is inferred. The two unresolved categories, Malus spp. and Unknown Fir, are also excluded. Both records in each of five published-score ties are retained, without assigning formal co-champion status. Four National Champion labels are preserved as the source’s Legacy Flags, not verified current national titles.</p>
      <p>All 445 records use 48 approximate county points from the Census Bureau’s 2025 Counties Gazetteer. Published addresses remain in record details and searches; markers do not locate individual trees, and visiting permission is not inferred. Each record links to its original PA Big Trees page.</p>
      <p>Details were checked for 384 included records. The remaining 61 retain public listing names, places, scores, dates, and flags, while unavailable measurements remain blank. Two source concerns are visible in their details: the London plane’s unusually large published circumference, and the Chestnut Oak’s report of severe decline. Source values are retained without correction. January 1 measurement dates may be legacy year placeholders; the snapshot does not establish current tree condition or eligibility.</p>
      <div className="course-actions"><a className="course-link" href={paChampionSource.registerUrl} target="_blank" rel="noreferrer">PA Big Trees register ↗</a><a className="course-link" href={paChampionSource.programUrl} target="_blank" rel="noreferrer">Pennsylvania Forestry Association ↗</a><a className="course-link" href={paChampionSource.scoringUrl} target="_blank" rel="noreferrer">Pennsylvania scoring guidance ↗</a><a className="course-link" href={paChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-DE">Delaware · 91 records across 76 species</h3>
      <p>The Delaware Forest Service’s official Big Trees Playground uses the Department of Agriculture’s FirstMap Big Tree Champs layer. Our October 6, 2026 snapshot compares all 207 records in that layer; the latest published ranking date is October 6, 2026. This GIS dataset is newer than the 2019 fifth-edition book. We retain all 79 entries with species rank 1, including multiple first-ranked trees in three species.</p>
      <p>We also include 12 lower-ranked records within five published points of their species maximum, applying the co-champion rule on printed page 3 (PDF page 5) of the 2019 book. These are labelled “Co-champion qualifier · five-point rule”: the qualification is derived, and their original ranks remain visible. Equal-score records are retained. The separate Unusual Big Trees layer is outside this selection. One rank-three ginkgo lacks a scientific name and is excluded; no identity is inferred.</p>
      <p>Names, addresses, counties, measurements, points, source ranks, and ranking dates are preserved with whitespace normalized. The dataset does not provide measurement dates or public-access permissions; ranking dates are shown separately. No current national title is inferred from the older book. Each tree links to its original FirstMap record and the official interactive map.</p>
      <p>All 91 records remain searchable and mapped: 86 use 31 approximate Census place points, including towns and census-designated places. Five records in Canterbury, Rockland, and Yorklyn use two county points because those names are not in the 2025 Census Places Gazetteer. Original place names remain visible. These markers do not locate individual trees. Delaware warns that many trees are on private property; confirm visiting guidance and obtain permission before entering.</p>
      <div className="course-actions"><a className="course-link" href={deChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Big Trees Playground ↗</a><a className="course-link" href={deChampionSource.dataUrl} target="_blank" rel="noreferrer">Delaware FirstMap dataset ↗</a><a className="course-link" href={`${deChampionSource.bookUrl}#page=5`} target="_blank" rel="noreferrer">2019 register &amp; co-champion rule ↗</a><a className="course-link" href={deChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census place geography ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-MI">Michigan · champions by highest published score</h3>
      <p>The Michigan Botanical Society’s public Big Tree Register, retrieved October 9, 2026, has a single sheet named Big_Tree_Data_2026-07-14 containing 667 trees. It includes smaller trees and has no explicit state-champion status or rank column. We select only the highest published Points within each scientific-name species category, retaining exact ties: 122 records across 120 categories. The other 545 lower-scoring trees are excluded. These are score-based leaders derived from the register, rather than independently confirmed official designations.</p>
      <p>Magnolia Xsoulangeana and Magnolia x soulangeana are grouped as one species for selection, with source names retained on individual records. The separate Variety field does not create additional champion categories. No near-score co-champions are inferred. Scores and measurements are preserved rather than recalculated to choose winners. The source’s National Champion flag is shown only as Michigan’s published label.</p>
      <p>All 122 records map to 38 approximate Census county points. County suffixes and “Gd. Traverse” are normalized for geography while the original county is retained. Individual-tree GPS coordinates, addresses, and location field notes are not copied into this map. Listing a location does not establish visiting permission. Public access remains unclassified.</p>
      <p>The source Verification Date is shown with that label. Five selected trees have dates older than ten years and one has no date. Those omissions and older dates are flagged without replacing a larger listed tree with a smaller one. Continued listing and historical condition notes do not confirm current tree health or recertification. Missing common names use another row of the same species where possible, with the fallback disclosed.</p>
      <div className="course-actions"><a className="course-link" href={miChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Michigan Big Tree Register ↗</a><a className="course-link" href={miChampionSource.programUrl} target="_blank" rel="noreferrer">Michigan Botanical Society program ↗</a><a className="course-link" href={miChampionSource.scoringUrl} target="_blank" rel="noreferrer">Michigan scoring guidance ↗</a><a className="course-link" href={miChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-IL">Illinois · 124 champion register entries</h3>
      <p>Illinois Extension’s official Big Tree map, retrieved October 8, 2026, contains 202 species slots. We include the 124 populated tree records across 106 published botanical categories, including 18 explicitly labeled co-champions. The 78 slots without a county or measurements are excluded. We retain every populated entry without choosing replacements or deriving additional co-champions from scores.</p>
      <p>Circumference is displayed in feet as published. Height and spread are also in feet; original scores are unchanged. The combined “Year listed/Last measured” field is preserved without treating every year as a measurement date. The Carolina silverbell has no circumference value; the eastern cottonwood retains its non-typical-form note. The dataset was last edited July 30, 2026; this does not establish current tree conditions.</p>
      <p>All 124 records use 47 approximate Census county points. “Saint Clair” is matched to St. Clair County, retaining the original county wording in the data. Public visiting access is unclassified. Individual tree coordinates, street locations, nominator details, and photographs are not imported.</p>
      <div className="course-actions"><a className="course-link" href={ilChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Illinois Big Tree map ↗</a><a className="course-link" href={ilChampionSource.programUrl} target="_blank" rel="noreferrer">Illinois Extension Big Tree Register ↗</a><a className="course-link" href={ilChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-FL">Florida · 311 champion and co-champion records</h3>
      <p>Florida Forest Service’s online register, retrieved October 8, 2026. Of 600 summary rows, 313 carry Florida Champion, Florida Co-Champion, National Champion, or National Co-Champion designations. Two identical repeated IDs (155 and 1270) are included once each, yielding 311 records. Challengers, emeritus, discontinued, nominees, and unknown designations are excluded. The import includes 48 co-champions. IDs 930 and 272 retain champion labels but list zero for every measurement and score; both remain with a source warning.</p>
      <p>Published names, measurements, scores, and titles are retained without re-ranking. National titles are Florida source designations and have not been independently verified against the national register. The summary does not supply measurement dates; individual source links provide further details. This snapshot does not confirm current tree condition.</p>
      <p>All records use 47 approximate county points from the Census Bureau’s 2025 Gazetteer. Tree coordinates, ownership, and visiting permission are not imported from the detail pages. Access remains unclassified here; consult the official record and current site guidance before visiting.</p>
      <p><a href={flChampionSource.registerUrl} target="_blank" rel="noreferrer">Florida Champion Tree Register ↗</a> · <a href={flChampionSource.programUrl} target="_blank" rel="noreferrer">Florida Forest Service program and public-land map ↗</a> · <a href={flChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></p>
      <h3 id="source-AL">Alabama · 145 published champion records</h3>
      <p>Alabama Forestry Commission’s 2025 Champion Tree List, retrieved October 8, 2026. All 145 tree rows across 134 scientific-name categories are retained, including multiple listed trees of the same species. Names, measurements, and published scores are preserved without recalculating rankings. PDF line breaks are joined; source spelling is retained.</p>
      <p>The year crowned and remeasurement deadline are shown separately. Neither supplies a measurement date, and historical deadlines are retained as published. This dated edition does not confirm current tree condition or status.</p>
      <p>All records map to 49 approximate county points from the Census Bureau’s 2025 Gazetteer. These markers do not locate individual trees. Ownership does not establish visiting permission; access remains unclassified. The program withholds private-land locations and directs public-land location requests to its coordinator.</p>
      <p><a href={alChampionSource.registerUrl} target="_blank" rel="noreferrer">2025 Alabama Champion Tree List ↗</a> · <a href={alChampionSource.programUrl} target="_blank" rel="noreferrer">Alabama Forestry Commission program ↗</a> · <a href={alChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></p>
      <h3 id="source-IN">Indiana · 93 current champion-list records</h3>
      <p>Indiana DNR Division of Forestry’s current champion table, retrieved October 8, 2026. All 93 populated tree rows are retained, including 10 explicitly labeled co-champions. Two empty species rows for sugar maple and Canada plum contain no county or measurements and are excluded. The page also names umbrella magnolia among species without a current champion despite supplying two populated co-champion rows; those records remain with a source note.</p>
      <p>Common and scientific names, measurements, published points, and co-champion designations are retained. The table supplies no measurement dates or stable tree IDs. Local record identities derive from the scientific name, county, and common name, so changes to those identity fields need reconciliation when refreshing. Published scores remain unchanged even where they differ from the measurement formula.</p>
      <p>All 93 records map to 40 approximate county points from the Census Bureau’s 2025 Gazetteer. “St Joseph” and “Laporte” are matched to St. Joseph and LaPorte, with the original wording preserved in each affected record. These points do not locate individual trees. Visiting permission is unclassified; use Indiana DNR’s current guidance before an outing.</p>
      <p><a href={inChampionSource.registerUrl} target="_blank" rel="noreferrer">Indiana DNR Big Tree Register ↗</a> · <a href={inChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></p>
      <h3 id="source-KY">Kentucky · 107 published register entries</h3>
      <p>Kentucky Division of Forestry’s official register, retrieved October 7, 2026. Each source card is imported once by its published ID, including 14 co-champion records. Names, measurements, published scores, nomination dates, and national labels are retained. National designations are not independently verified. Three measurement-date fields contain “pdf”; these remain undated with a source note. Swamp cottonwood appears both as a record and in the page’s list of species without champions; its record carries a status warning.</p>
      <p>All 107 records use approximate Census points for 57 counties. Source county fields containing co-champion labels or “Co” are preserved alongside the matched county. The source labels 61 records private; other records remain unclassified for visiting access. Published coordinates are not used as map markers or evidence of permission. Consult the official program before planning a visit.</p>
      <p><a href={kyChampionSource.registerUrl} target="_blank" rel="noreferrer">Kentucky’s Champion Trees ↗</a> · <a href={kyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></p>
      <h3 id="source-GA">Georgia · 403 published register entries</h3>
      <p>Georgia Forestry Commission’s official register, retrieved October 7, 2026. The list contains 407 rows representing 403 unique published IDs. Repeated IDs 1950 and 1673 are counted once, using the first listed detail page; conflicting summary variants are documented in the import audit. Measurements, measurement dates, and Georgia/National and co-champion fields follow individual records where available; any summary-list fallback is identified in its record notes. Blank or ambiguous designations remain qualified; national labels are not independently verified. Published scores are retained even when they differ from the listed measurements.</p>
      <p>398 entries use 99 approximate county points; five have no published county. Markers use representative county points from the Census Bureau’s 2025 Counties Gazetteer. Missing counties remain unmapped. County-name capitalization is matched to Census names; source wording is retained. Public access is unclassified, and no individual tree coordinates or owner information are imported. Follow the official record for location details and current visiting guidance.</p>
      <p><a href={gaChampionSource.registerUrl} target="_blank" rel="noreferrer">Georgia Forestry Commission Champion Tree Register ↗</a> · <a href={gaChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></p>
      <h3 id="source-TN">Tennessee · 183 published champion entries</h3>
      <p>The University of Tennessee’s Current Champion Trees list is maintained by its School of Natural Resources with the Tennessee Division of Forestry. This October 7, 2026 snapshot retains all 183 entries across 164 published scientific names, including repeated species. It does not derive additional champion or national titles from scores. The page supplies no measurement dates or edition date.</p>
      <p>182 records use 38 approximate Census county points. One record lists “Lafayette” as a county; that source value is retained and left unmapped. Public access and exact tree locations are not supplied. County markers do not provide directions to a tree.</p>
      <p><a href={tnChampionSource.registerUrl} target="_blank" rel="noreferrer">UT Current Champion Trees ↗</a> · <a href={tnChampionSource.programUrl} target="_blank" rel="noreferrer">Tennessee program and scoring guidance ↗</a></p>
      <h3 id="source-SC">South Carolina · 196 state-designated champions</h3>
      <p>Clemson University’s official South Carolina Champion Tree Database, retrieved October 7, 2026. We include all 196 records explicitly marked “State Champ” from 269 published records. The 66 runners-up and seven other entries are excluded. The champions span 190 published botanical categories, with multiple designated trees retained in six categories. Inclusion follows Clemson’s designation rather than recalculated scores or an inferred co-champion threshold.</p>
      <p>Names, measurements, scores, dates, and condition reports are retained with whitespace normalized. Ten records carry a National Champ label and one a National Co-Champ label; these are Clemson’s published designations, not independently verified current national titles. The Tungoil tree (record 250) has no published circumference or score, so both remain blank. Published score discrepancies remain visible in record details.</p>
      <p>Clemson’s map labels its submission_date field “Measurement Date”; we display it as “Date shown by Clemson” to preserve that context. Twelve champions have no date. The layer reports its last data edit as November 25, 2025, which is separate from individual record dates and our retrieval date. Older measurements and condition descriptions do not establish current tree conditions.</p>
      <p>All 196 trees use 35 approximate county points from the Census Bureau’s 2025 Gazetteer. These points do not locate individual trees or provide directions. Public visiting access is unclassified; land ownership and champion designation are not treated as permission to visit. Personal contact fields, owner details, street addresses, exact tree geometry, photographs, and free-text remarks are not imported.</p>
      <div className="course-actions"><a className="course-link" href={scChampionSource.registerUrl} target="_blank" rel="noreferrer">Official South Carolina database ↗</a><a className="course-link" href={scChampionSource.programUrl} target="_blank" rel="noreferrer">Clemson Champion Tree Program ↗</a><a className="course-link" href={scChampionSource.measuringUrl} target="_blank" rel="noreferrer">Clemson measurement guidance ↗</a><a className="course-link" href={scChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-NC">North Carolina · 346 champions and co-champions · September 2026</h3>
      <p>The N.C. Forest Service’s current champion roster, September 2026 edition, posted October 2 and retrieved October 7, 2026. We include 165 champions and 181 entries explicitly marked co-champions, across 237 published botanical categories. Inclusion follows the official roster and labels; scores are not used to override those designations. The program describes a ten-point co-champion rule and is reviewing eligibility and inspecting its champions.</p>
      <p>The workbook contains 347 populated tree rows. Green hawthorn Tree ID 727 appears twice with identical measurements, county and access labels; row 40 spells its genus “Carataegus”, while row 101 gives “Crataegus”. We retain row 101 once. IDs 75, 330 and 682 are each assigned to two distinct trees; both records remain with separate map links and source-row references. The sugarberry in row 69 has no Tree ID and remains included with that omission explained.</p>
      <p>Names, measurements, points, co-champion labels and access authorizations are preserved. Eight records carry a national champion label; these report the state source’s designation without independent confirmation. One “TBD” national status remains undecided. Measurement dates are absent and are not inferred from the workbook date. Published score discrepancies remain visible in the details.</p>
      <p>All 346 trees map to 76 approximate county points from the Census Bureau’s 2025 Gazetteer. The source explicitly marks owner-authorized public access and viewing for 238 records and “No” for 108. Exact locations are withheld for landowner privacy, including for public-access trees. Contact the program for location information and confirm visiting arrangements; county markers do not provide directions.</p>
      <div className="course-actions"><a className="course-link" href={ncChampionSource.registerUrl} target="_blank" rel="noreferrer">Official North Carolina champion roster ↗</a><a className="course-link" href={ncChampionSource.workbookUrl} target="_blank" rel="noreferrer">Download the NC workbook ↗</a><a className="course-link" href={ncChampionSource.programUrl} target="_blank" rel="noreferrer">NC Champion Tree Program ↗</a><a className="course-link" href={ncChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-WV">West Virginia · 159 highest-scoring records · 2025 edition</h3>
      <p>The WV Division of Forestry’s 2025 Flowering Common and Conifers Common workbooks, retrieved October 7, 2026, contain 533 registered trees. They include runners-up and do not provide a general champion-status field. We retain only the maximum published Big Tree Points in each named tree category. This gives 159 records across 157 categories, including exact-score ties for common serviceberry and pawpaw. These are score-based leaders, not independently certified state-champion designations; no wider co-champion threshold is inferred.</p>
      <p>Selection uses common-name categories so botanical spelling errors and annotations do not create extra winners. “Chineese Chestnut” and “Chinese Chestnut” are treated as one category, then excluded because the leading entry pairs Chinese Chestnut with Castanea dentata, the American chestnut name. No runner-up is promoted. Lower-scoring entries are excluded even when they carry an undated national or co-champion annotation. National annotations on retained leaders remain source notes, without asserting a current national title.</p>
      <p>Names, measurements, published scores, and last-inspection years are retained with whitespace normalized. Annotations are separated from scientific names into source notes. Nonstandard circumference heights and multi-stem notation remain visible. Scores are not recalculated for selection. The workbook’s “Last Inspection” year is displayed as an inspection date, not as the edition or retrieval date.</p>
      <p>All 159 records map to 35 approximate county points from the Census Bureau’s 2025 Gazetteer. Source spellings “Pendelton” and “Pochontas” are matched to Pendleton and Pocahontas, with the original wording recorded. Town names remain visible; the state explains that “near” may mean many miles away. Exact tree positions and visiting permission are not inferred. The separate public-property workbook includes private entries, so its title is not used to classify public access.</p>
      <div className="course-actions"><a className="course-link" href={wvChampionSource.floweringUrl} target="_blank" rel="noreferrer">WV flowering register · 2025 Excel ↗</a><a className="course-link" href={wvChampionSource.conifersUrl} target="_blank" rel="noreferrer">WV conifer register · 2025 Excel ↗</a><a className="course-link" href={wvChampionSource.programUrl} target="_blank" rel="noreferrer">WV Big Tree Program ↗</a><a className="course-link" href={wvChampionSource.definitionsUrl} target="_blank" rel="noreferrer">WV measurement definitions ↗</a><a className="course-link" href={wvChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-VA">Virginia · 369 state champion records</h3>
      <p>Virginia Tech’s current State Champions list, retrieved October 7, 2026. Every entry was checked against its individual record for an alive status and explicit Virginia Champion designation. Multiple designated trees within a botanical category are retained. The live list is newer than the January 2026 PDF; that PDF also includes trees outside the champion selection.</p>
      <p>Names, measurements, measurement years, published points, and national labels are preserved. National labels report Virginia Tech’s designation, not independent confirmation of current national standing. Each card links to its original record. Public visiting permission is not inferred from a champion designation.</p>
      <p>All 369 records span 281 published botanical categories and map to 86 approximate county or independent-city points from the Census Bureau’s 2025 Gazetteer. Cities remain separate from similarly named counties. Tree GPS coordinates and personal owner/contact details are not imported.</p>
      <div className="course-actions"><a className="course-link" href={vaChampionSource.registerUrl} target="_blank" rel="noreferrer">Virginia Tech champion list ↗</a><a className="course-link" href={vaChampionSource.mapUrl} target="_blank" rel="noreferrer">Official Virginia champion map ↗</a><a className="course-link" href={vaChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county and city geography ↗</a></div>
      <h3 id="source-MD">Maryland · 274 state-designated champions</h3>
      <p>The Maryland Big Tree Program’s State Champion Trees table, linked from Maryland DNR, was retrieved October 6, 2026. All 274 entries carry an explicit State designation. They span 239 published botanical categories, including species, hybrids, and cultivars. Multiple designated trees within a category are retained without recalculating eligibility or inventing co-champion labels. Thirteen entries also carry a National label; that is Maryland’s published designation, not independent confirmation of current national standing.</p>
      <p>The snapshot preserves original record links, tree IDs, common and scientific names, measurements, points, towns, and last-measured years. It includes native and introduced trees as listed in the current register. The source explicitly marks 127 trees publicly accessible and 147 not publicly accessible; those labels power the public-access filter. Check the original record and current visiting guidance before an outing.</p>
      <p>All 274 records are searchable and mapped at 24 approximate Census county or independent-city points. Baltimore City is kept distinct from Baltimore County. Published towns and addresses remain on the cards, but these markers do not locate individual trees. Tree GPS coordinates and personal owner or nominator details are not imported. Measurement years are separate from this snapshot’s retrieval date.</p>
      <div className="course-actions"><a className="course-link" href={mdChampionSource.registerUrl} target="_blank" rel="noreferrer">Maryland State Champion Trees ↗</a><a className="course-link" href={mdChampionSource.programUrl} target="_blank" rel="noreferrer">Maryland DNR Big Tree Program ↗</a><a className="course-link" href={mdChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <p>Map tiles: © OpenStreetMap contributors. Tree Yoga School created this independent exploration of the {Object.keys(stateNames).length} registers.</p>
    </section>
  </main><SiteFooter /></>;
}

