import type { Metadata } from "next";
import Link from "next/link";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
import ChampionExplorer from "./champion-explorer";
import { championSource, nhChampionSource, vtChampionSource, meChampionSource, riChampionSource, ctChampionSource, nyChampionSource, njChampionSource, paChampionSource, deChampionSource, mdChampionSource, stateNames, sourceDates } from "../../lib/champion-trees";
import "leaflet/dist/leaflet.css";
import { championTrees, championManifest } from "../../lib/champion-tree-data";

export const metadata: Metadata = {
  title: "Champion Tree Map | Tree Yoga School",
  description: "Explore 2,354 champion and score-based leader records across Massachusetts, New Hampshire, Vermont, Maine, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, and Maryland. Browse an interactive town and county map, measurements, source records, and tree practices.",
};

export default function ChampionTreesPage() {
  return <><SiteHeader /><main id="content" className="champion-page">
    <section className="champion-intro">
      <Link className="lesson-back" href="/trees">The Tree Library · Out in the world</Link>
      <p className="section-kicker">Eleven states to explore · Champion Tree Map</p>
      <h1>Meet the giants<br />among us.</h1>
      <p className="lesson-lede">Remarkable trees, rooted in real places. Explore champion trees across Massachusetts, New Hampshire, Vermont, Maine, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, and Maryland, discover their scale, and let curiosity lead you into a deeper relationship with the trees around you.</p>
      <div className="champion-stats"><span><strong>{championTrees.length.toLocaleString("en-US")}</strong> listed trees</span><span><strong>{championManifest.reduce((total, state) => total + state.mapped, 0).toLocaleString("en-US")}</strong> mapped trees</span><span><strong>{Object.keys(stateNames).length}</strong> states to explore</span></div>
    </section>
    <section className="champion-source-dates" aria-label="State register dates"><h2>Which lists are we exploring?</h2><div className="champion-date-grid">{championManifest.map(s => <a key={s.state} href={`#source-${s.state}`}><strong>{s.name}</strong><span>{sourceDates[s.state]}</span><small>{s.listed.toLocaleString("en-US")} listed · {s.mapped.toLocaleString("en-US")} mapped</small></a>)}</div><p className="champion-location-note">Mapped means an approximate town, Census place, or county point is available, not an exact tree location. Retrieval dates describe our snapshot, not when a tree was measured.</p></section>
    <ChampionExplorer manifest={championManifest} />
    <section className="champion-about" aria-labelledby="about-champions">
      <div><p className="section-kicker">Reading the register</p><h2 id="about-champions">What makes a champion?</h2><p>A champion’s distinction is its size within its species or category; the score does not measure age. DCR’s champion score combines trunk circumference in inches, height in feet, and one quarter of average crown spread in feet.</p><p className="champion-formula">Circumference + height + ¼ crown spread = points</p><p>Measurements and scores appear as published, including zeros and occasional discrepancies. NH’s table labels height and crown spread in feet, but does not specify circumference units. NH detail cards retain those values without assigning units; nomination dates are not measurement dates.</p><p>This map combines Massachusetts’ May 2026 workbook with Maine’s 2020 PDF and the NH and Vermont registers retrieved October 6, 2026. It is a snapshot, not a live register or confirmation of current tree conditions. Only NH entries marked “State” are included. Multiple state-designated records for a species are retained; county-only and historical-status entries are excluded. Vermont includes only records marked as confirmed champions in its official map; multiple confirmed records for a species are retained. Maine includes all 146 entries in the 2020 state register, including multiple entries for some species. Its year of last measurement is shown without inventing a month or day. Rhode Island adds 155 usable rank-one entries from its March 24, 2026 table; one malformed row is excluded and documented below. Connecticut includes 400 champions and 104 co-champions explicitly designated in its champion lists; other notable and historic trees are excluded. New York adds 210 champions and co-champions from its January 31, 2025 register. New Jersey adds 206 records explicitly designated Champion, Co-Champion, Heritage Champion, or National Champion by NJDEP. Pennsylvania adds 445 score-based leaders from PA Big Trees, with qualifications for ties, legacy flags, and incomplete detail checks. Delaware adds 79 rank-one records and 12 additional qualifiers under its published five-point co-champion rule, using the current FirstMap dataset. Maryland adds 274 entries explicitly marked State in its current champion table, retaining multiple designated trees in a botanical category.</p></div>
      <div><p className="section-kicker">A thoughtful visit</p><h2>Let the tree be your teacher.</h2><p>Maryland, New York, Pennsylvania, and some New Jersey and Delaware records use approximate county points; other markers use town or Census place points. New York’s register supplies counties only. Massachusetts, Rhode Island, and Connecticut publish addresses or sites for some records; NH’s register provides a town and county. Maine’s 2020 register lists towns and townships, without exact tree locations or public-access designations. Vermont publishes coordinates for 24 trees marked publicly accessible. Those cards include a separate link to the published tree position, while map markers remain at town locations. Vermont’s other 67 records are labelled private with no public access. A place name does not establish public access. Check visiting guidance and request permission for private property.</p><p>For NH outings, <a href={nhChampionSource.publicMapUrl} target="_blank" rel="noreferrer">UNH’s public Big Tree Map ↗</a> offers a separate selection of trees on public property or land open to visitors. Its selection includes different champion levels and is not the same as this state-only list.</p><p>You can practice with an ordinary tree nearby, too. Take a few minutes to notice its form, the life around it, and what changes when you give it your attention.</p><Link className="course-link" href="/lessons/first-five-minutes">Your First Five Minutes with a Tree</Link></div>
    </section>
    <section className="champion-sources" aria-label="Map sources"><h2>Sources & map notes</h2>
      <h3 id="source-MA">Massachusetts · 139 records</h3><p>The supplied Massachusetts DCR Champion Trees workbook, May 2026. Original names, measurements, location descriptions, and notes are retained. Approximate town centers come from MassGIS municipal polygon centroids retrieved October 6, 2026. “Manchester” is mapped to Manchester-by-the-Sea.</p>
      <div className="course-actions"><a className="course-link" href={championSource.workbookUrl} download>Download the original MA list (.xlsx)</a><a className="course-link" href={championSource.programUrl} target="_blank" rel="noreferrer">DCR Legacy Tree Program ↗</a><a className="course-link" href={championSource.geographyUrl} target="_blank" rel="noreferrer">MassGIS geography ↗</a></div>
      <h3 id="source-NH">New Hampshire · 93 state-designated records</h3><p>NH Big Trees’ public register, retrieved October 6, 2026. These records cover 77 scientific-name labels. Original names, measurements, nomination dates, tree IDs, and status designations are preserved. Each detail card links to its source table page; look for the listed Tree ID.</p><p>Approximate NH municipality points come from the U.S. Census Bureau’s 2025 County Subdivisions Gazetteer. East Swanzey uses Swanzey’s point, Rye Beach uses Rye’s, Sanbornville uses Wakefield’s, and “W. Franklin” uses Franklin’s. The source spelling “Boscowen” is interpreted as Boscawen in Merrimack County. Cards retain the original place names and explain these mappings. Points do not locate villages or individual trees.</p>
      <div className="course-actions"><a className="course-link" href={nhChampionSource.registerUrl} target="_blank" rel="noreferrer">NH Big Trees register ↗</a><a className="course-link" href={nhChampionSource.programUrl} target="_blank" rel="noreferrer">NH Big Tree Program ↗</a><a className="course-link" href={nhChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census geography ↗</a></div>
      <h3 id="source-VT">Vermont · 91 confirmed champions</h3><p>The official Vermont Big Tree List’s public data view, retrieved October 6, 2026, filtered to confirmed champions. Common and scientific names, measurements, data collection dates, and access labels are retained; excess whitespace is normalized. One record has no common name. Missing names and source discrepancies are identified in the details.</p><p>Vermont’s register marks 24 records publicly accessible and 67 with no public access. Visibility from a road does not grant entry. Only coordinates explicitly published for public trees are linked; private tree coordinates are not included. Town markers use representative points from the Census Bureau’s 2025 County Subdivisions Gazetteer.</p><p>The program’s September 2026 notice says activities are temporarily on hold following a staffing transition. This map preserves the published register as a dated snapshot; check the original program for updates.</p><div className="course-actions"><a className="course-link" href={vtChampionSource.registerUrl} target="_blank" rel="noreferrer">Vermont Big Tree List ↗</a><a className="course-link" href={vtChampionSource.programUrl} target="_blank" rel="noreferrer">Vermont Big Tree Program ↗</a><a className="course-link" href={vtChampionSource.geographyUrl} target="_blank" rel="noreferrer">Vermont Census geography ↗</a></div>
      <h3 id="source-ME">Maine · 146 records · 2020 edition</h3><p>The Maine Forest Service’s Register of Big Trees, downloaded October 6, 2026. The official program still links to the 2020 edition. All 146 table entries are retained, including multiple trees of the same species. The PDF’s original spellings, asterisks, measurements, scores, and last-measured years are preserved. The PDF has no asterisk legend, so symbols are not interpreted as verified national or co-champion designations. Published score discrepancies are flagged in record details.</p><p>These records use 65 approximate town and township points. Most come from the Census Bureau’s 2025 County Subdivisions Gazetteer. Bradstreet and Moosehead Junction use Maine GIS township polygon centroids. South Paris is grouped under Paris; “Milton Plantation” uses Milton’s unorganized-territory point; “Bradstreet Twp.” is matched to Bradstreet Twp. Original place names remain on the cards. Counties are added from this official geography, not from the tree register.</p><p>The register does not publish addresses, exact tree coordinates, or access permissions. Maine entries therefore do not appear under “Source confirms public access.” A 2020 listing does not establish a tree’s current condition or champion status.</p><div className="course-actions"><a className="course-link" href={meChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Maine register · 2020 PDF ↗</a><a className="course-link" href={meChampionSource.programUrl} target="_blank" rel="noreferrer">Maine Forest Service Big Trees ↗</a><a className="course-link" href={meChampionSource.geographyUrl} target="_blank" rel="noreferrer">Maine Census geography ↗</a><a className="course-link" href={meChampionSource.townshipUrl} target="_blank" rel="noreferrer">Maine GIS townships ↗</a></div>
      <h3 id="source-RI">Rhode Island · 155 records · March 24, 2026 edition</h3><p>The Rhode Island Tree Council’s Helen Walker Raleigh Champion Trees Program register, retrieved October 6, 2026. All 155 usable entries marked rank 1 are included, including multiple entries for a species. Names, addresses, measurements, and published scores are preserved with whitespace normalized. The page’s older gallery count differs from the dated table used here. Measurement dates are not provided.</p><p>The table’s final Zelkova row contains numbers in the species, common-name, town, and address columns. That malformed row is excluded until its identity and location can be confirmed. No replacement record is invented.</p><p>The 28 municipality points and county names come from the Census Bureau’s 2025 County Subdivisions Gazetteer. One empress-tree entry places “Swan Point Cemetery” in the city/town column; its original fields are retained and it is grouped under Providence, where <a href={riChampionSource.cemeteryUrl} target="_blank" rel="noreferrer">the cemetery’s own website ↗</a> locates it. Published addresses do not establish visiting permission; Rhode Island entries are unclassified for public access.</p><div className="course-actions"><a className="course-link" href={riChampionSource.registerUrl} target="_blank" rel="noreferrer">Rhode Island champion register ↗</a><a className="course-link" href={riChampionSource.geographyUrl} target="_blank" rel="noreferrer">Rhode Island Census geography ↗</a></div>
      <h3 id="source-CT">Connecticut · 504 champions and co-champions</h3><p>Connecticut’s Notable Trees, hosted by Connecticut College and supported by the Connecticut College Arboretum, Connecticut Botanical Society, and Connecticut Urban Forest Council. Retrieved October 6, 2026. The common-name and scientific-name champion lists are matched by Tree ID and checked against individual records. Only explicit Connecticut champion and co-champion designations are included: 400 champions and 104 co-champions. The register includes species, hybrids, and cultivated varieties; multiple designated trees remain separate.</p><p>Original names, measurements, points, measurement dates, named-tree labels, and published addresses are retained with whitespace normalized. Cards use the individual record’s common name; alternate names from the alphabetized list appear in searchable source notes. Each card links to its original record for photographs, directions, and additional context. Published locations do not establish public access, and no access permission is inferred. Locations withheld by the program remain undisclosed. Map markers are approximate municipality points.</p><p>The 97 Connecticut town points come from the Census Bureau’s 2025 County Subdivisions Gazetteer. The county filter is expanded to “County or planning region” because current Census geography uses Connecticut’s nine planning regions as county equivalents. These region names are added from Census geography, not from the tree register.</p><div className="course-actions"><a className="course-link" href={ctChampionSource.registerUrl} target="_blank" rel="noreferrer">Connecticut champions by common name ↗</a><a className="course-link" href={ctChampionSource.scientificUrl} target="_blank" rel="noreferrer">Connecticut champions by scientific name ↗</a><a className="course-link" href={ctChampionSource.geographyUrl} target="_blank" rel="noreferrer">Connecticut Census geography ↗</a><a className="course-link" href={ctChampionSource.regionsUrl} target="_blank" rel="noreferrer">Connecticut planning regions ↗</a></div>
      <h3 id="source-NY">New York · 210 champions and co-champions · January 31, 2025</h3><p>NYS DEC’s Big Tree Register, retrieved October 6, 2026. The scientific-name and common-name PDFs contain the same 210 records: 162 champions and 48 co-champions. Asterisks identify co-champions. The lists are reconciled across all measurements, counties, regions, nominators, and years; two scientific names are clipped differently between layouts, noted on their cards. Published measurements, names, and scores are retained.</p><p>The register gives counties without towns, addresses, tree coordinates, or access permissions. All 210 records use 37 approximate county points from the Census Bureau’s 2025 Counties Gazetteer. County markers do not identify the tree’s location. “Montgomer,” “St. Lawrenc,” “Cattaragus,” and “Wyomng” are matched to Montgomery, St. Lawrence, Cattaraugus, and Wyoming; original wording remains in source notes. No visiting permission is inferred.</p><p>New York publishes crown points, equal to one quarter of average crown spread in feet. Cards show that original contribution explicitly rather than labeling it as full crown spread. Last-measured years remain distinct from the register’s edition date.</p><div className="course-actions"><a className="course-link" href={nyChampionSource.registerUrl} target="_blank" rel="noreferrer">New York register · scientific names ↗</a><a className="course-link" href={nyChampionSource.commonUrl} target="_blank" rel="noreferrer">New York register · common names ↗</a><a className="course-link" href={nyChampionSource.programUrl} target="_blank" rel="noreferrer">NYS DEC Big Tree Program ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-NJ">New Jersey · 206 champion-designated records</h3><p>The New Jersey Forest Service’s official NJDEP Big and Heritage Trees public dataset, retrieved October 6, 2026. The dataset reports a last edit of March 19, 2026; individual measurement dates are not supplied. We include only records with permission to list marked YES and an explicit champion status: 182 Champion, 9 Co-Champion, 8 Heritage Champion, and 7 National Champion. National designations are shown as NJDEP’s labels, without independently asserting current national status. Published rankings are retained even where they differ from first place; inclusion follows the official status field.</p><p>All 206 records remain searchable. We map 110 records to 59 unambiguously matched municipalities within their published counties. The other 96 records use 17 clearly labeled county points because the municipality is a village, ambiguous, misspelled, or inconsistent with its county. Original municipality names and published addresses remain in the details. Points come from the Census Bureau’s 2025 Gazetteer; they do not locate individual trees. Tree coordinates are not imported, and permission to list is not treated as permission to visit.</p><p>Botanical-name code underscores are displayed as spaces. Names, measurements, rankings, and status designations otherwise remain as published. NJDEP’s crown field is labeled “Crown Average (in.)” although its scoring guidance uses feet. We display the original crown value without assigning a confirmed unit, converting it, or recalculating the score. This inconsistency is explained on each record.</p><div className="course-actions"><a className="course-link" href={njChampionSource.registerUrl} target="_blank" rel="noreferrer">Official New Jersey map &amp; registry ↗</a><a className="course-link" href={njChampionSource.programUrl} target="_blank" rel="noreferrer">NJDEP Big &amp; Heritage Trees ↗</a><a className="course-link" href={njChampionSource.dataUrl} target="_blank" rel="noreferrer">NJDEP public dataset ↗</a><a className="course-link" href={njChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census municipality geography ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-PA">Pennsylvania · 445 score-based leaders</h3>
      <p>The Pennsylvania Forestry Association’s PA Big Trees register, using the supplied October 2026 extraction. All 1,520 public listing records were compared by source genus and species category, retaining each maximum published score. Source categories include species, hybrids, cultivars, varieties, and forms; their original names are preserved. These are derived state-leader candidates, not an independently certified champion-only roster.</p>
      <p>The extraction identified 446 leaders across 441 named botanical categories. We exclude the <a href="https://pabigtrees.com/morris-arboretum-100-e-northwestern-ave-phila-tr20100930204444730" target="_blank" rel="noreferrer">Northern Pin Oak marked “removed” ↗</a>, leaving 445 records across 440 categories. No successor is inferred. The two unresolved categories, Malus spp. and Unknown Fir, are also excluded. Both records in each of five published-score ties are retained, without assigning formal co-champion status. Four National Champion labels are preserved as the source’s Legacy Flags, not verified current national titles.</p>
      <p>All 445 records use 48 approximate county points from the Census Bureau’s 2025 Counties Gazetteer. Published addresses remain in record details and searches; markers do not locate individual trees, and visiting permission is not inferred. Each record links to its original PA Big Trees page.</p>
      <p>Details were checked for 384 included records. The remaining 61 retain public listing names, places, scores, dates, and flags, while unavailable measurements remain blank. Two source concerns are visible in their details: the London plane’s unusually large published circumference, and the Chestnut Oak’s report of severe decline. Source values are retained without correction. January 1 measurement dates may be legacy year placeholders; the snapshot does not establish current tree condition or eligibility.</p>
      <div className="course-actions"><a className="course-link" href={paChampionSource.registerUrl} target="_blank" rel="noreferrer">PA Big Trees register ↗</a><a className="course-link" href={paChampionSource.programUrl} target="_blank" rel="noreferrer">Pennsylvania Forestry Association ↗</a><a className="course-link" href={paChampionSource.scoringUrl} target="_blank" rel="noreferrer">Pennsylvania scoring guidance ↗</a><a className="course-link" href={paChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-DE">Delaware · 91 records across 76 species</h3>
      <p>The Delaware Forest Service’s official Big Trees Playground uses the Department of Agriculture’s FirstMap Big Tree Champs layer. Our October 6, 2026 snapshot compares all 207 records in that layer; the latest published ranking date is October 6, 2026. This GIS dataset is newer than the 2019 fifth-edition book. We retain all 79 entries with species rank 1, including multiple first-ranked trees in three species.</p>
      <p>We also include 12 lower-ranked records within five published points of their species maximum, applying the co-champion rule on printed page 3 (PDF page 5) of the 2019 book. These are labelled “Co-champion qualifier · five-point rule”: the qualification is derived, and their original ranks remain visible. Equal-score records are retained. The separate Unusual Big Trees layer is outside this selection. One rank-three ginkgo lacks a scientific name and is excluded; no identity is inferred.</p>
      <p>Names, addresses, counties, measurements, points, source ranks, and ranking dates are preserved with whitespace normalized. The dataset does not provide measurement dates or public-access permissions; ranking dates are shown separately. No current national title is inferred from the older book. Each tree links to its original FirstMap record and the official interactive map.</p>
      <p>All 91 records remain searchable and mapped: 86 use 31 approximate Census place points, including towns and census-designated places. Five records in Canterbury, Rockland, and Yorklyn use two county points because those names are not in the 2025 Census Places Gazetteer. Original place names remain visible. These markers do not locate individual trees. Delaware warns that many trees are on private property; confirm visiting guidance and obtain permission before entering.</p>
      <div className="course-actions"><a className="course-link" href={deChampionSource.registerUrl} target="_blank" rel="noreferrer">Official Big Trees Playground ↗</a><a className="course-link" href={deChampionSource.dataUrl} target="_blank" rel="noreferrer">Delaware FirstMap dataset ↗</a><a className="course-link" href={`${deChampionSource.bookUrl}#page=5`} target="_blank" rel="noreferrer">2019 register &amp; co-champion rule ↗</a><a className="course-link" href={deChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census place geography ↗</a><a className="course-link" href={nyChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <h3 id="source-MD">Maryland · 274 state-designated champions</h3>
      <p>The Maryland Big Tree Program’s State Champion Trees table, linked from Maryland DNR, was retrieved October 6, 2026. All 274 entries carry an explicit State designation. They span 239 published botanical categories, including species, hybrids, and cultivars. Multiple designated trees within a category are retained without recalculating eligibility or inventing co-champion labels. Thirteen entries also carry a National label; that is Maryland’s published designation, not independent confirmation of current national standing.</p>
      <p>The snapshot preserves original record links, tree IDs, common and scientific names, measurements, points, towns, and last-measured years. It includes native and introduced trees as listed in the current register. The source explicitly marks 127 trees publicly accessible and 147 not publicly accessible; those labels power the public-access filter. Check the original record and current visiting guidance before an outing.</p>
      <p>All 274 records are searchable and mapped at 24 approximate Census county or independent-city points. Baltimore City is kept distinct from Baltimore County. Published towns and addresses remain on the cards, but these markers do not locate individual trees. Tree GPS coordinates and personal owner or nominator details are not imported. Measurement years are separate from this snapshot’s retrieval date.</p>
      <div className="course-actions"><a className="course-link" href={mdChampionSource.registerUrl} target="_blank" rel="noreferrer">Maryland State Champion Trees ↗</a><a className="course-link" href={mdChampionSource.programUrl} target="_blank" rel="noreferrer">Maryland DNR Big Tree Program ↗</a><a className="course-link" href={mdChampionSource.geographyUrl} target="_blank" rel="noreferrer">Census county geography ↗</a></div>
      <p>Map tiles: © OpenStreetMap contributors. Tree Yoga School created this independent exploration of the eleven registers.</p>
    </section>
  </main><SiteFooter /></>;
}
