import { pageMetadata } from "../../lib/site-seo";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
export const metadata = pageMetadata("/about", "About | Tree Yoga School", "Meet Alex Julian and the roots of Tree Yoga School: yoga, meditation, observation, and learning with living trees.");
export default function Page() { return <><SiteHeader /><main id="content" className="lesson community-page">
<section className="lesson-intro"><p className="section-kicker">The school · Founded by Alex Julian</p><h1>Nature is the teacher.</h1><p className="lesson-lede">Tree Yoga School begins with a simple relationship: a person giving their attention to a living tree.</p><p>Founded by Alex Julian, the school brings together yoga, meditation, walking, and the practice of learning from nature. Its foundation is Alex’s original <i>Tree Yoga School</i> book, published in 2023. This growing digital school offers new ways to bring those teachings outdoors.</p><div className="course-actions"><a className="button primary" href="/begin-here">Find your beginning →</a><a className="button secondary" href="/book">Explore the original book</a></div></section>
<section className="lesson-section"><p className="section-kicker">From reading to relationship</p><h2>A school you can take outside.</h2><div className="lesson-options"><article><h3>Practice with a tree.</h3><p>Begin with observation. Sit, stand, walk, or pause from a place that fits you. Tree Hugging offers a gentle embrace, a light touch, or time nearby.</p><a className="course-link" href="/tree-hugging">Explore Tree Hugging →</a></article><article><h3>Get to know it.</h3><p>The Tree Library pairs botanical observation with contemplative invitations. The Champion Map and Trees to Visit help you discover remarkable trees and places.</p><a className="course-link" href="/tree-visits">Find a tree to visit →</a></article></div></section>
<section className="lesson-section"><h2>Rooted in a book. Growing in public.</h2><p>The original book remains the source of the school’s teachings. New practices, reading companions, and species interpretations are marked as adaptations. Botanical references and photo credits sit beside the content they support. Personal and contemplative meanings are invitations to reflect, rather than fixed meanings everyone must feel.</p><p>The Champion Map brings published registers together. Source dates, approximate locations, and visiting access are part of the story. A listed record is a starting point for learning; current observations can help us improve it.</p><a className="course-link" href="/big-tree-volunteers">Help the school grow through observation →</a></section>
<section className="lesson-section lesson-pause"><h2>Let go and let’s grow.</h2><p>Return to one tree. Notice what changes. Bring a little more attention into the rest of your day.</p><div className="course-actions"><a className="button light" href="/return-to-your-tree">Return to your tree →</a><a className="button light" href="/contact">Contact the school</a></div></section></main><SiteFooter /></>; }
