import { pageMetadata } from "../../lib/site-seo";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
export const metadata = pageMetadata("/big-tree-volunteers", "Big Tree Volunteers | Tree Yoga School", "A beginning for people who want to contribute tree observations, source corrections, and careful visiting information.");
export default function Page() { return <><SiteHeader /><main id="content" className="lesson community-page">
<section className="lesson-intro"><p className="section-kicker">An idea taking root</p><h1>Big Tree Volunteers.</h1><p className="lesson-lede">People who return. Trees we get to know. A school that grows through careful attention.</p><p>Alex’s vision is a connected community of trees, humans, and AI: people in each state helping keep tree stories and visiting information useful. We are beginning modestly, with observations and corrections. There is no organized state network or scheduled volunteer program yet.</p><div className="course-actions"><a className="button primary" href="/contact#contribute">Contribute an observation →</a><a className="button secondary" href="/contact#contribute">Express volunteer interest</a></div></section>
<section className="lesson-section"><h2>Three useful ways to begin.</h2><div className="volunteer-grid"><article><p className="section-kicker">01 · Check a source</p><h3>Make a record clearer.</h3><p>Report a broken link, a spelling mismatch, a newer register, or a measurement copied incorrectly. Include the school page or map record ID, the source link, and what needs changing.</p></article><article><p className="section-kicker">02 · Return to a tree</p><h3>Describe what you see.</h3><p>From a permitted place, note the visit date, seasonal changes, and visible condition. Distinguish what you observed from what you think it means. Your own photographs can help.</p></article><article><p className="section-kicker">03 · Improve a visit</p><h3>Help someone arrive.</h3><p>Share changed opening hours, a closed path, or an updated official access page. Date your observations and describe the route you actually used; conditions and accessibility can vary.</p></article></div></section>
<section className="lesson-section"><h2>A helpful observation is a careful one.</h2><ul><li>Include the tree or record, general place, date, your observations, and any supporting source.</li><li>Use permitted paths and respect the landowner’s guidance. A map marker is not permission to visit.</li><li>Leave bark, roots, branches, plants, and wildlife undisturbed. No climbing or measuring is needed to contribute.</li><li>Keep private addresses, owner contact details, and undisclosed tree locations private. Ask permission before sharing them.</li><li>Send only photographs you took or have permission to share; tell us your preferred credit and publication permission.</li></ul><p>Observations are contributions for review. They do not automatically update the map or establish champion status. For official nominations and measurements, use the relevant state register linked from the Champion Map.</p><div className="course-actions"><a className="button primary" href="/contact#contribute">Share a correction or observation →</a><a className="course-link" href="/champion-trees">Find the state’s official register →</a></div></section>
<section className="lesson-section course-start"><h2>Start with one tree.</h2><p>You do not need to find a champion. A familiar tree and a dated note are enough to begin the habit of returning.</p><a className="course-link" href="/return-to-your-tree">Try the return practice and journal →</a></section></main><SiteFooter /></>; }
