import Link from "next/link";
import SiteHeader from "../components/site-header";
import TreeEmbrace from "../components/tree-embrace";
import { pageMetadata } from "../../lib/site-seo";
import { treeHuggingPractice, treeHuggingResearch } from "../../lib/tree-hugging";

export const metadata = pageMetadata("/tree-hugging", "Tree Hugging: Practice & Benefits | Tree Yoga School", "A gentle tree-hugging meditation: how to begin, what research suggests, and how attention becomes care for the living world.");

function Source({ number, id }: { number: number; id: string }) {
  return <a className="hug-citation" href={`#research-${id}`} aria-label={`Read research source ${number}`}>[{number}]</a>;
}

export default function TreeHugging() {
  return <>
    <SiteHeader />
    <main id="content" className="hug-page">
      <section className="hug-hero" aria-labelledby="hug-title">
        <div className="hug-hero-copy"><p className="section-kicker">Tree Hugging · A central practice of Tree Yoga School</p><h1 id="hug-title">Hug a tree.<br /><em>Come back<br />to yourself.</em></h1><p className="hug-lede">Bring your attention close to something alive. A gentle embrace, a quiet breath, a moment of belonging.</p><div className="hero-actions"><a className="button hug-button" href="#practice">Try the practice ↓</a><a className="hug-text-link" href="#benefits">Explore the benefits ↗</a></div><p className="hug-hero-foot">One tree. Your own pace. An open invitation.</p></div>
        <div className="hug-hero-art"><span className="hug-orbit-label">Rooted in relationship</span><TreeEmbrace /><p>Notice the life you are touching.</p></div>
      </section>
      <nav className="hug-page-nav" aria-label="Tree Hugging sections"><a href="#practice">The practice</a><a href="#benefits">The benefits</a><a href="#connections">The connections</a><a href="#research">The research</a></nav>

      <section className="hug-introduction hug-shell"><p className="section-kicker">A living meeting</p><div><h2>Let the world<br />become personal.</h2><p>Tree Hugging is a simple meditation in relationship with a living tree. Pause beside it. Rest your hands or arms gently against its trunk, if that suits your body and the place. Notice what changes when your attention moves from thinking about life to meeting it.</p><p>For Tree Yoga School, the embrace is an expression of presence, gratitude, and affection for the living world. Some people experience it as deeply restorative or healing in a personal sense. You are welcome to bring your own meaning—and to discover it slowly.</p><p className="hug-small-note">Touch is always optional. Being beside a tree is a complete practice.</p></div></section>

      <section id="practice" className="hug-practice hug-shell" aria-labelledby="hug-practice-title">
        <div className="hug-section-heading"><div><p className="section-kicker">01 / The practice</p><h2 id="hug-practice-title">An embrace.<br />A few minutes.<br /><em>A place to return.</em></h2></div><div><p>Read the steps once, then let the screen rest. There is no special posture to achieve and no feeling you have to produce.</p><Link className="button primary" href="/practice/tree-hugging">Open outdoor practice →</Link><p className="hug-small-note">Large type · Optional timer · Printable steps</p></div></div>
        <ol className="hug-steps">{treeHuggingPractice.steps.map((step, i) => <li key={step.title}><span className="hug-step-number" aria-hidden="true">0{i + 1}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol>
        <div className="hug-adaptations"><h3>Make the embrace your own.</h3><div><p><strong>One hand.</strong> A light palm can be enough. You do not need to reach around the trunk.</p><p><strong>Seated or nearby.</strong> Keep your usual supports. A wheelchair, bench, or accessible path can be your place of practice.</p><p><strong>No touch.</strong> Rest your gaze on the tree, listen, and notice your own breath. Stop or change position whenever you wish.</p></div></div>
      </section>

      <section id="benefits" className="hug-benefits" aria-labelledby="hug-benefits-title"><div className="hug-shell"><p className="section-kicker">02 / The benefits</p><div className="hug-section-heading"><h2 id="hug-benefits-title">A softer pace.<br /><em>A wider sense of life.</em></h2><p>Research gives us reasons to value time with trees. The strongest evidence concerns nature exposure and forest bathing; direct evidence for tree hugging is still limited. These are possibilities to explore, rather than outcomes to expect.</p></div><div className="hug-benefit-grid">
        <article><span>01 — Rest</span><h3>Room to settle.</h3><p>Forest studies have observed short-term changes consistent with relaxation, including lower cortisol and pulse rate than in city settings. <Source number={1} id="forest" /> A gentle tree embrace offers a simple way to pause within that environment.</p></article>
        <article><span>02 — Attention</span><h3>Out of the thought loop.</h3><p>A small study of 90-minute nature walks found reduced self-reported rumination in the nature group. <Source number={2} id="attention" /> In this practice, texture and sound become places to return when thoughts keep circling.</p></article>
        <article><span>03 — Touch</span><h3>A tangible point of presence.</h3><p>Laboratory research on touching wood found relaxation responses relative to some other surfaces. <Source number={3} id="touch" /> Living bark is different; here, its texture can be a sensory anchor for meditation.</p></article>
        <article><span>04 — Relationship</span><h3>Connection that becomes care.</h3><p>Feeling connected to nature is associated with more reported environmental care. <Source number={4} id="care" /> Let your visit lead to a small act of stewardship: respecting roots, learning the species, or caring for this place.</p></article>
      </div><p className="hug-evidence-note">Tree embracing also appears in an exploratory forest-therapy study, alongside several other activities. <Source number={5} id="embrace" /> It does not establish what a hug alone does. This is a wellbeing and contemplative practice, not a medical treatment.</p></div></section>

      <section id="connections" className="hug-connections hug-shell" aria-labelledby="hug-connections-title"><p className="section-kicker">03 / The connections</p><div className="hug-section-heading"><h2 id="hug-connections-title">From embrace<br /><em>to relationship.</em></h2><p>Tree Yoga School brings the embrace into a larger practice of attention, meaning, and care. Explore these connections through your own experience.</p></div><div className="hug-connection-list">
        <article><span>Yoga & meditation</span><h3>One tree. One point.</h3><p>Let the tree become a point of focus. Return gently when attention wanders. This is a living expression of the school’s practices of presence and one-pointed focus.</p><Link href="/lessons/meditation-with-a-tree">Explore meditation with a tree →</Link></article>
        <article><span>Forest bathing</span><h3>Receive the surroundings.</h3><p>Shinrin-yoku invites attention to the forest atmosphere. <Source number={1} id="forest" /> Tree Hugging can be one pause within that experience: listen beyond the trunk to the whole place.</p><Link href="/lessons/tree-yoga-hiking">Bring this pause into a walk →</Link></article>
        <article><span>Gratitude & reciprocity</span><h3>Leave something better.</h3><p>Affection can become action. Learn the tree’s name, honor its space, and notice the other lives around it. The practice deepens when care travels beyond the moment of contact.</p><Link href="/trees">Meet your tree in the Library →</Link></article>
      </div></section>

      <section className="hug-care hug-shell" aria-labelledby="hug-care-title"><div><p className="section-kicker">Care belongs inside the practice</p><h2 id="hug-care-title">A gentle hug.<br /><em>A light footprint.</em></h2></div><div><p>Choose a place where you are allowed to be. Follow site rules and stay outside fences and protective barriers. A champion designation or map marker does not grant access or permission to touch.</p><p>Use light contact, keep your own balance, and leave the tree intact. Avoid fragile bark, young saplings, nests, damaged limbs, irritating plants, and slippery ground. Skip touch if you have broken or irritated skin.</p><p>Respect roots and soft ground; repeated trampling can compact soil. For a group visit, protect the tree by keeping gathering areas on established paths or durable surfaces. The National Park Service explains why root zones and bark need protection. <a className="hug-citation" href="https://www.nps.gov/articles/000/preservation-matters-landscape-maintenance-protecting-historic-trees-during-construction.htm" target="_blank" rel="noreferrer">Read tree-care guidance ↗</a></p></div></section>

      <section id="research" className="hug-research hug-shell" aria-labelledby="hug-research-title"><p className="section-kicker">04 / The research</p><h2 id="hug-research-title">Curiosity, with roots.</h2><p className="hug-research-intro">Follow the evidence. Each source below distinguishes what was studied from the connections we make in the practice. Research reviewed October 9, 2026.</p><div className="hug-research-list">{treeHuggingResearch.map(source => <details key={source.id} id={`research-${source.id}`}><summary><span className="hug-source-number">0{source.number}</span><span><strong>{source.title}</strong><small>{source.citation} · {source.year}</small></span><span className="hug-details-icon" aria-hidden="true">+</span></summary><div className="hug-source-body"><p>{source.finding}</p><p><strong>What this means here:</strong> {source.limit}</p><a href={source.url} target="_blank" rel="noreferrer">Read the original research ↗</a></div></details>)}</div></section>

      <section className="hug-questions hug-shell" aria-labelledby="hug-questions-title"><h2 id="hug-questions-title">A little room for questions.</h2><div className="hug-question-grid"><article><h3>What if I feel nothing?</h3><p>You do not have to feel calm, connected, or moved. Notice your actual experience. Curiosity is enough, and you can stop at any time.</p></article><article><h3>Do I need a forest?</h3><p>A permitted tree beside an accessible path or in a neighborhood park is enough to begin this practice. The forest-study results do not automatically apply to every setting.</p></article><article><h3>What does “healing” mean here?</h3><p>It may describe someone’s experience of comfort, perspective, or reconnection. It is personal language, not a claim that a tree embrace cures illness.</p></article><article><h3>Will there be Tree Hug events?</h3><p>We envision gentle gatherings where people meet trees, practice together, and care for the place. That is a future direction; no events are scheduled yet.</p></article></div></section>

      <section className="hug-closing"><div className="hug-shell"><p className="section-kicker">Begin close to home</p><h2>You do not need<br />a famous tree.<br /><em>You need a moment.</em></h2><p>Let one ordinary tree become someone you notice.</p><div className="hero-actions"><Link className="button hug-button" href="/practice/tree-hugging">Take the practice outside →</Link><Link className="button light" href="/tree-visits">Explore trees to visit</Link></div><p className="hug-closing-map"><Link href="/champion-trees">Curious about remarkable trees? Explore the Champion Map ↗</Link></p></div></section>
    </main><footer><p>Founded by Alex Julian · Rooted in the original Tree Yoga School.</p><p>© 2026 Tree Yoga School</p></footer>
  </>;
}
