import { pageMetadata } from "../../lib/site-seo";
import SiteHeader from "../components/site-header";
import SiteFooter from "../components/site-footer";
export const metadata = pageMetadata("/return-to-your-tree", "Return to Your Tree | Tree Yoga School", "A seasonal practice: revisit one tree, observe changes, and keep a simple printable observation journal.");
export default function Page() { return <><SiteHeader /><main id="content" className="lesson community-page">
<section className="lesson-intro"><p className="section-kicker">A seasonal practice · About 5–10 minutes</p><h1>Return to your tree.</h1><p className="lesson-lede">One tree. Different days. A relationship that grows through noticing.</p><p>Choose a familiar tree in a place you can revisit with permission. It might be beside an accessible path, in a garden, or visible from a window. Return when it suits you: after a few weeks, at a change of season, or whenever you are curious.</p><div className="course-actions"><a className="button primary" href="/return-to-your-tree/journal">Open the observation journal →</a><a className="button secondary" href="/printables/return-to-your-tree-journal.pdf" download>Download printable PDF</a></div></section>
<section className="lesson-section"><h2>Five steps for each return.</h2><ol className="lesson-steps"><li><h3>Arrive in a familiar place.</h3><p>Pause on stable ground with your usual supports. Choose a safe, permitted viewpoint, keep paths clear, and let your breathing stay natural. Contact with the tree is optional.</p></li><li><h3>Look before you compare.</h3><p>Take a minute to meet today’s tree. Notice its outline, light, buds or foliage, exposed bark, and the ground nearby. Listen for life around it.</p></li><li><h3>Notice one change and one continuity.</h3><p>Compare with your previous note or memory. What changed? What seems much the same? Record “not sure” when the view or conditions make a comparison difficult.</p></li><li><h3>Make a small record.</h3><p>Write the date, weather, and a few concrete observations. Sketch one detail or take your own photo from the same permitted viewpoint. Separate what you saw from what you inferred.</p></li><li><h3>Carry one question forward.</h3><p>What would you like to look for next time? Notice your own experience too. Leave the tree and surroundings undisturbed, then choose a possible next visit.</p></li></ol></section>
<section className="lesson-section"><h2>Follow the tree’s season.</h2><div className="lesson-options"><article><h3>Buds and emerging growth</h3><p>Look for swelling buds, unfolding leaves or needles, and flowers if present. Note what is absent as well as what appears.</p></article><article><h3>A leafy or growing period</h3><p>Notice shade, leaf color, new shoots, and visitors you can observe without disturbing them.</p></article><article><h3>Fruits and changing foliage</h3><p>Look for cones or fruits, changes in color, and naturally fallen material. Some trees keep foliage rather than shedding it.</p></article><article><h3>A quieter or dormant period</h3><p>Explore branching patterns, retained foliage, buds, and the changing light. Skip a visit when weather or ground conditions make it unsuitable.</p></article></div><p>These are observation prompts, not a calendar every species follows. Local climate, evergreen foliage, and individual trees make each return different.</p></section>
<section className="lesson-section lesson-pause"><h2>What is changing in the tree—and in you?</h2><p>A dated observation and a sentence of reflection are enough. There is no streak to maintain and no particular feeling to achieve.</p></section>
<section className="lesson-section"><h2>Keep the relationship growing.</h2><p>This is a new practice inspired by the original book’s chapter on small beginnings, changing seasons, and a place to return to.</p><div className="course-actions"><a className="course-link" href="/book/when-and-where">Read When and Where →</a><a className="course-link" href="/big-tree-volunteers">Share a useful observation →</a><a className="course-link" href="/trees">Get to know your species →</a></div></section></main><SiteFooter /></>; }
