import type { Tree } from "./trees";
import { plainsLibraryImages } from "./tree-library-plains-images";

export const plainsLibraryTrees: readonly Tree[] = [
  {
    ...plainsLibraryImages["osage-orange"],
    slug: "osage-orange", name: "Osage Orange", species: "Osage Orange", scientificName: "Maclura pomifera",
    themes: ["Boundaries", "Resilience", "Care"],
    invitation: "Find a comfortable distance. Let a clear boundary make room for care.",
    introduction: "An Osage orange invites you to notice edges: the outline of a crown, the meeting of leaf and sky, the space between your body and a branch. Its history as a living fence offers a starting point for reflection on boundaries. Begin with the individual tree, rather than asking its toughness to explain your life.",
    identity: [
      { title: "Leaves and branches", text: "Simple, alternate leaves have smooth to slightly wavy margins and pointed tips. Many trees carry stout thorns on their twigs; some cultivated forms are thornless. Observe without reaching into branches." },
      { title: "Fruit and bark", text: "Female trees can bear large, wrinkled, yellow-green fruits. Mature bark is orange-brown and deeply ridged. This is a mulberry-family tree, not a citrus orange; leave fruit and sap undisturbed." },
      { title: "Place", text: "Native to parts of Texas, Oklahoma, and Arkansas, Osage orange has been planted and naturalized widely. Dense, thorny growth was historically used for hedgerows. Look for several features before naming a tree." },
    ],
    seasons: "Spring brings new leaves and small flowers. Fruits on female trees mature in autumn, when foliage can turn yellow. In winter, notice the irregular branch outline and ridged bark. Fallen fruits can make footing uneven; choose a clear viewing place.",
    energies: [
      { title: "Boundaries", observation: "The crown has a visible outline, and many twigs carry thorns.", meaning: "Consider a boundary that protects your attention while allowing connection. You can care without reaching into every situation.", question: "What deserves a little protected space?" },
      { title: "Resilience", observation: "The tree's shape includes bends, crowded growth, and openings.", meaning: "Let its particular form prompt a flexible response to difficulty. Resilience can include changing your position and asking for support.", question: "Where could flexibility help you continue?" },
      { title: "Care", observation: "Fruit, leaves, and branches occupy a place shared with wildlife.", meaning: "Practice care by leaving room for the lives already here. Attention need not become possession.", question: "What can you appreciate without taking?" },
    ],
    practiceTitle: "A boundary with room for kindness.",
    practiceIntroduction: "An original five-minute practice of distance, attention, and boundaries. Sit or stand with your usual supports; no touching or special breathing is needed.",
    practice: [
      { title: "Find a comfortable distance", text: "Choose stable, permitted ground away from thorns, loose fruit, and damaged branches. Notice the space between you and the tree. Adjust until looking feels comfortable." },
      { title: "Trace an edge", text: "Follow a short section of the crown with your eyes, then pause at one leaf or branch. Let your breath remain natural. Notice where the tree's outline meets the sky." },
      { title: "Name one boundary", text: "Quietly consider one limit you would like to express: a time to rest, a task you can decline, or space to finish something. Choose simple words without rehearsing an argument." },
      { title: "Leave room for kindness", text: "Widen your view to the surrounding place. Imagine stating your boundary calmly, with care for yourself and others. Choose one small next action and finish at your own pace." },
    ],
    reflection: "What boundary could help you care more sustainably?",
    principles: "Presence, balance, and connection", sourceUrl: "https://plants.ces.ncsu.edu/plants/maclura-pomifera/",
  },
  {
    ...plainsLibraryImages["chinkapin-oak"],
    slug: "chinkapin-oak", name: "Chinkapin Oak", species: "Chinkapin Oak", scientificName: "Quercus muehlenbergii",
    themes: ["Discernment", "Steadiness", "Curiosity"],
    invitation: "Look twice. Give one small detail enough attention to change your first impression.",
    introduction: "Chinkapin oak offers a practice in looking beyond the first resemblance. Its toothed leaves may surprise someone expecting the deep lobes of a familiar oak. Discernment begins with comparing what is actually visible and allowing uncertainty to remain while you look again.",
    identity: [
      { title: "Leaf margins", text: "Alternate, elongated leaves have coarse, rounded teeth rather than deeply cut lobes. The upper surface is green; the underside is paler. Compare the entire leaf shape as well as its edge." },
      { title: "Acorns and bark", text: "Small acorns mature in one growing season and sit in gray, scaly cups. Bark is light gray and develops irregular fissures. Acorns and buds help distinguish this oak from similar-looking trees." },
      { title: "Place and comparison", text: "A member of the white oak group, chinkapin oak is native to eastern and central North America and often grows on limestone or rocky uplands. It is distinct from dwarf chinkapin oak; use a regional identification key." },
    ],
    seasons: "Spring can reveal hanging pollen catkins and new leaves. Acorns ripen by autumn; leaf color varies through yellow and brown tones. Winter exposes branch structure and pale bark. A feature missing on this visit may become visible on the next.",
    energies: [
      { title: "Discernment", observation: "Leaf teeth, acorn cups, and bark offer different identification clues.", meaning: "Separate an observation from an assumption. Let several small clues guide you before settling on a conclusion.", question: "What have you seen, and what have you assumed?" },
      { title: "Steadiness", observation: "One tree remains your reference while you compare its details.", meaning: "Return to something concrete when thoughts become complicated. A steady point can support careful decisions.", question: "What can anchor your next decision?" },
      { title: "Curiosity", observation: "A closer view reveals differences within a familiar-looking leaf.", meaning: "Allow a first impression to become a question. Curiosity can soften the need to be immediately right.", question: "What might another look reveal?" },
    ],
    practiceTitle: "Three clues. One unhurried look.",
    practiceIntroduction: "An original observation practice for distinguishing what you notice from what you infer. A view from a path or bench is enough.",
    practice: [
      { title: "Choose one visible feature", text: "Settle on stable, permitted ground with your usual supports. Find a leaf still attached to an accessible branch, or look at the bark from a distance. Leave living growth untouched." },
      { title: "Describe before naming", text: "Quietly name three visible qualities: an edge, a color, and a shape. Use ordinary words. If you cannot see a detail clearly, let it stay unknown." },
      { title: "Look a second time", text: "Return to the same feature and notice one thing your first description missed. Then compare it with another feature of the tree. Keep breathing naturally." },
      { title: "Carry the distinction", text: "Consider one decision in your day. Identify something you know and something you still need to learn. Choose a modest way to gather that missing information, then widen your attention and finish." },
    ],
    reflection: "What changed when you gave your first impression another look?",
    principles: "Presence, one-pointed focus, and curiosity", sourceUrl: "https://plants.ces.ncsu.edu/plants/quercus-muehlenbergii/",
  },
  {
    ...plainsLibraryImages["post-oak"],
    slug: "post-oak", name: "Post Oak", species: "Post Oak", scientificName: "Quercus stellata",
    themes: ["Endurance", "Simplicity", "Steadiness"],
    invitation: "Choose one small, repeatable act. Let enough be enough for today.",
    introduction: "A post oak can be a companion for considering sustainable effort. Look at its particular branches and the ground where it grows. The practice is an invitation to choose a manageable commitment, with room for rest and changing circumstances.",
    identity: [
      { title: "Cross-shaped leaves", text: "Simple, alternate leaves usually have five rounded lobes. The large middle pair can give the leaf a cross-like outline. The underside is pale and hairy; compare several leaves because shapes vary." },
      { title: "Crown and acorns", text: "The crown is often dense and irregular, with twisting upper branches. Brown acorns have scaly cups. It belongs to the white oak group; rounded lobes alone do not establish a species identification." },
      { title: "Place", text: "Native to the central and eastern United States, post oak often grows on dry, rocky, or relatively poor soils. Its tolerance of drought is a botanical trait, not a suggestion that people should ignore their needs." },
    ],
    seasons: "Spring brings leaves and catkins. Summer offers a full crown; autumn brings acorns and variable leaf color. Bare winter branches reveal the tree's irregular structure. Return to one familiar detail and notice both continuity and change.",
    energies: [
      { title: "Endurance", observation: "An established tree carries its growth in a lasting branch structure.", meaning: "Consider an effort you can continue without exhausting yourself. A pause can belong to a lasting commitment.", question: "What pace would let you keep returning?" },
      { title: "Simplicity", observation: "One leaf provides a small, bounded place to begin looking.", meaning: "Reduce a large intention to an action you can actually do. Simplicity makes room for attention.", question: "What is enough for this visit?" },
      { title: "Steadiness", observation: "Branches hold a recognizable outline through seasonal changes.", meaning: "Let a familiar point support you without requiring everything else to remain the same.", question: "What can stay steady while your plans adjust?" },
    ],
    practiceTitle: "One modest commitment.",
    practiceIntroduction: "An original five-minute practice of simplicity and sustainable effort. Use a comfortable seated or standing position and let your breath remain natural.",
    practice: [
      { title: "Arrive without a task list", text: "Choose stable, permitted ground clear of damaged branches. Sit or stand with your usual supports. For this moment, let looking at the tree be the whole task." },
      { title: "Return to one shape", text: "Choose a leaf outline or a bend in a branch. Notice it, allow your eyes to rest, then return. There is no need to count breaths or hold your attention perfectly." },
      { title: "Make an intention smaller", text: "Think of something you want to continue. Reduce it to one repeatable act: a few minutes of practice, one message, or a short walk suited to your circumstances." },
      { title: "Include a resting point", text: "Decide when that small act will be enough and how you will stop or rest. Notice the wider scene again. Leave with a commitment you can revise when your needs change." },
    ],
    reflection: "What becomes possible when your commitment is small enough to repeat?",
    principles: "Perseverance, balance, and one-pointed focus", sourceUrl: "https://plants.ces.ncsu.edu/plants/quercus-stellata/",
  },
  {
    ...plainsLibraryImages["kentucky-coffeetree"],
    slug: "kentucky-coffeetree", name: "Kentucky Coffeetree", species: "Kentucky Coffeetree", scientificName: "Gymnocladus dioicus",
    themes: ["Spaciousness", "Patience", "Rest"],
    invitation: "Notice the space between branches. Give an unfinished thing time to unfold.",
    introduction: "Kentucky coffeetree asks for a change of scale: one enormous compound leaf contains many smaller leaflets, while bare branches leave generous openings to the sky. Its seasonal rhythm offers a prompt for patience. You do not have to make every interval productive.",
    identity: [
      { title: "Twice-compound leaves", text: "Very large leaves divide into smaller branches that carry many leaflets. One leaflet is not a whole leaf. Follow the arrangement visually without pulling a branch toward you." },
      { title: "Bark and pods", text: "Gray-brown bark has deep fissures and scaly ridges. Female trees can produce thick, flattened brown pods. Leaves, seeds, and pod pulp are toxic; this observation practice includes no tasting or preparation." },
      { title: "Place", text: "Native to central and eastern North America, Kentucky coffeetree has an open, irregular crown. Male and female flowers are usually on separate trees, and some planted cultivars produce no pods." },
    ],
    seasons: "Leaves emerge relatively late in spring and can fall relatively early in autumn, turning yellow. Flowers appear in late spring to early summer. Pods on female trees may persist into winter. Look at the tree's present season without interpreting bare branches alone as a sign of poor health.",
    energies: [
      { title: "Spaciousness", observation: "Openings between stout branches leave sky visible within the crown.", meaning: "Attend to the intervals as well as the objects. A little space can make an experience easier to meet.", question: "Where would a little room help?" },
      { title: "Patience", observation: "Leaves arrive and depart on a rhythm that can differ from nearby trees.", meaning: "Let the tree prompt reflection on your own timing. An unfinished process does not always need to be rushed.", question: "What could you allow more time?" },
      { title: "Rest", observation: "Bare branches can remain a conspicuous part of this tree's year.", meaning: "Consider a pause as part of a cycle rather than a missing achievement. Your experience may call for rest or for a small beginning.", question: "What kind of pause would support you?" },
    ],
    practiceTitle: "Let the spaces count.",
    practiceIntroduction: "An original five-minute practice of spacious attention and patience. Observe from stable ground, with seated and distance options equally welcome.",
    practice: [
      { title: "Find a broad view", text: "Choose a permitted viewing place clear of damaged branches and fallen pods. Settle with your usual supports. Keep your head in a comfortable position rather than straining upward." },
      { title: "Look into an opening", text: "Find one opening between branches, or between groups of leaflets. Let the background be part of what you notice. Keep your breathing easy and unforced." },
      { title: "Alternate space and shape", text: "Move your attention from the opening to its bordering branch or leaf, then back. Notice how the whole scene includes both. You need not fill the interval with a thought." },
      { title: "Give something time", text: "Name one unfinished thing you can approach patiently. Choose either a small next step or a deliberate pause, according to your needs. Return to the full scene and close the practice." },
    ],
    reflection: "What did you notice when the spaces became part of the view?",
    principles: "Presence, patience, and balance", sourceUrl: "https://plants.ces.ncsu.edu/plants/gymnocladus-dioicus/",
  },
  {
    ...plainsLibraryImages["slippery-elm"],
    slug: "slippery-elm", name: "Slippery Elm", species: "Slippery Elm", scientificName: "Ulmus rubra",
    themes: ["Gentleness", "Attention", "Care"],
    invitation: "Let a close look be gentle. You can notice texture without touching it.",
    introduction: "Slippery elm offers a useful surprise: its name sounds smooth, while its leaves have a rough surface. Use that contrast as a prompt to loosen expectations and look carefully. Gentleness here belongs to the way you attend, not to a claim about a healing effect.",
    identity: [
      { title: "Leaves", text: "Alternate leaves have uneven bases, doubly toothed margins, and a rough upper surface. The underside is paler and hairy. Compare several features with other elms; do not strip a leaf to test its texture." },
      { title: "Flowers and fruit", text: "Small greenish-red flowers form clusters in late winter or early spring, followed by flat, winged fruits called samaras. Seasonal timing varies with location and weather." },
      { title: "Bark and care", text: "Gray bark develops narrow ridges and shallow furrows. Slippery elm is susceptible to Dutch elm disease. Leave bark attached; observation does not require harvesting or exposing the reddish inner bark." },
    ],
    seasons: "Early flowers and spring samaras can precede the full summer crown. Autumn foliage turns dull yellow; winter reveals twigs and bark. Look for what is present, and let a return visit add another part of the picture.",
    energies: [
      { title: "Gentleness", observation: "Fine details remain visible without removing leaves or bark.", meaning: "Try an attentive approach that asks less of the tree and of yourself. Looking can be enough.", question: "How can your attention become less demanding?" },
      { title: "Attention", observation: "An uneven leaf base and repeated teeth interrupt a simple outline.", meaning: "Notice a detail that a familiar name might lead you to overlook. Let the particular tree correct your expectation.", question: "What becomes clear when you slow down?" },
      { title: "Care", observation: "Bark remains part of a living trunk, with its own texture and pattern.", meaning: "Value something without requiring it to provide a product or an answer. Care can mean leaving it intact.", question: "What can you leave better protected?" },
    ],
    practiceTitle: "A close look, a gentle return.",
    practiceIntroduction: "An original five-minute practice of visual texture and gentle attention. Touch is optional in Tree Yoga; this practice uses looking alone.",
    practice: [
      { title: "Choose an easy view", text: "Sit or stand on stable, permitted ground using your normal supports. Choose a patch of bark or an attached leaf you can see comfortably, clear of damaged branches." },
      { title: "Notice a texture visually", text: "Follow one ridge, vein, or toothed edge with your eyes. Notice light and shadow across it. Leave the tree untouched and let your breath continue naturally." },
      { title: "Return without correcting yourself", text: "When your attention wanders, notice where it went and come back gently. Treat each return as another look, without scoring your concentration." },
      { title: "Take gentleness into the day", text: "Widen your view to the tree and its surroundings. Consider one ordinary task you could approach with less pressure. Choose a kinder pace or smaller step, then finish." },
    ],
    reflection: "What changed when you returned without judging the wandering?",
    principles: "Presence, one-pointed focus, and compassion", sourceUrl: "https://plants.ces.ncsu.edu/plants/ulmus-rubra/",
  },
  {
    ...plainsLibraryImages["butternut"],
    slug: "butternut", name: "Butternut", species: "Butternut", scientificName: "Juglans cinerea",
    themes: ["Care", "Stewardship", "Connection"],
    invitation: "Notice one living neighbor. Let appreciation lead to one informed act of care.",
    introduction: "Butternut brings stewardship into a quiet encounter. Look at one tree before thinking about a whole forest: its crown, its place, and the lives nearby. Care can begin with learning what is present and choosing an action suited to that place, rather than trying to solve everything at once.",
    identity: [
      { title: "Compound leaves", text: "Leaves have many toothed leaflets arranged along a central stalk, usually including a terminal leaflet. Compare this arrangement with black walnut and other walnuts; one feature alone is not enough." },
      { title: "Nuts and bark", text: "Elongated nuts develop inside green husks. Older gray bark has relatively flat ridges and shallow furrows. Observe fallen nuts without collecting them, and leave living bark attached." },
      { title: "Place and stewardship", text: "Native to eastern Canada and the central and eastern United States, butternut has suffered severe losses from butternut canker. Identification, disease assessment, and conservation decisions call for qualified local guidance." },
    ],
    seasons: "Spring to early summer brings catkins and small female flowers. Summer displays compound leaves; nuts mature in autumn. The open crown and bark are visible in winter. Repeat observations can record changes, but a photograph alone cannot establish a tree's health.",
    energies: [
      { title: "Care", observation: "One individual tree occupies a particular place among other living things.", meaning: "Let care begin with noticing someone or something specifically. A concrete encounter can make a broad intention manageable.", question: "What nearby life could you learn about?" },
      { title: "Stewardship", observation: "A visit can leave the tree, roots, and surrounding growth undisturbed.", meaning: "Choose care that respects the place and the knowledge of those responsible for it. Good intentions benefit from information.", question: "What should you learn before acting?" },
      { title: "Connection", observation: "Leaves, nuts, ground, and neighboring plants belong to one shared scene.", meaning: "Consider how a small action affects more than its immediate subject. You are part of the surroundings you observe.", question: "Who else belongs in your picture of care?" },
    ],
    practiceTitle: "Observe. Learn. Care.",
    practiceIntroduction: "An original five-minute stewardship practice. Begin with an accessible view; no collecting, pruning, or diagnosing is part of the practice.",
    practice: [
      { title: "Meet this individual", text: "Choose stable, permitted ground clear of damaged branches. Sit or stand with your usual supports. Notice one tree and the plants around it without trampling roots or undergrowth." },
      { title: "Record one observation", text: "Choose a visible detail and describe it plainly to yourself. If useful, make a brief note or take a photograph from the path. Separate what you see from a guess about disease or age." },
      { title: "Ask a stewardship question", text: "Consider what you would need to learn before helping: the species, who cares for the site, or which local conservation program offers guidance. Leave that question open if the answer is not yet available." },
      { title: "Choose informed care", text: "Pick one modest next step, such as consulting a regional tree guide or learning about a local butternut conservation effort. Do not move nuts, wood, or bark between sites. Widen your attention and finish." },
    ],
    reflection: "What small act of care could begin with better understanding?",
    principles: "Connection, compassion, and presence", sourceUrl: "https://plants.ces.ncsu.edu/plants/juglans-cinerea/",
  },
];
