import type { Tree } from "./trees";
import { mapTreeImages } from "./tree-library-map-images";

export const mapPracticeTrees: readonly Tree[] = [
  {
    slug: "green-ash", name: "Green Ash", species: "Green ash", scientificName: "Fraxinus pennsylvanica",
    ...mapTreeImages["green-ash"],
    themes: ["Adaptability", "Renewal", "Care"],
    invitation: "Notice the present conditions. Find one adjustment that helps you continue.",
    introduction: "Meet the individual tree before deciding what its story means. A leafy crown, a bare branch, or a distant view can each offer a place to begin. Give your attention to what is actually here.",
    identity: [
      { title: "Leaves and twigs", text: "Opposite, compound leaves usually have five to nine leaflets, whose margins may be toothed or smooth. Compare the arrangement of whole leaves on a twig, not only the leaflets. Other ashes can look similar." },
      { title: "Bark and seeds", text: "Mature bark develops interlacing ridges. Female trees can bear narrow, winged seeds called samaras. Use several features together; bark alone is not a reliable identification." },
      { title: "Place and care", text: "Native to central and eastern North America, green ash grows in floodplains, riverbanks, and other moist habitats. Emerald ash borer threatens this species. View declining trees from an established safe place, away from damaged branches." },
    ],
    seasons: "Spring brings flowers before or with unfolding leaves. Summer reveals compound foliage; autumn leaves often turn yellow, and winged seeds may remain on female trees. Winter exposes opposite branching and buds. Local conditions and tree health affect what you see.",
    energies: [
      { title: "Adaptability", observation: "The tree stands in particular conditions of soil, light, and weather.", meaning: "Let those conditions prompt an honest look at your own situation. An adjustment can begin with recognizing what is available today.", question: "What small change would fit your current conditions?" },
      { title: "Renewal", observation: "A branch may carry leaves, buds, or the space left by an earlier season.", meaning: "Use the visible stage as an invitation to begin from where you are. Renewal need not repeat the shape of an earlier effort.", question: "What could you begin again in a workable form?" },
      { title: "Care", observation: "A closer look may reveal both growth and damage.", meaning: "Allow concern to become one practical act of care. You do not have to turn every difficulty into an uplifting lesson.", question: "What needs attention before you ask more of it?" },
    ],
    practiceTitle: "Adjust to the conditions.",
    practiceIntroduction: "An original five-minute practice in adaptability and renewal, beginning with the scene before you.",
    practice: [
      { title: "Find a supported view", text: "Sit or stand on stable, permitted ground using your usual supports. Choose a distant viewpoint if the tree has damaged limbs. Keep your breathing natural." },
      { title: "Describe today", text: "Notice one detail of the tree and one detail of its surroundings. Name each plainly, without deciding whether the scene is good or bad." },
      { title: "Notice what you need", text: "Check whether your seat, stance, or viewing distance suits you. Make one comfortable adjustment if useful, or remain as you are." },
      { title: "Choose a workable beginning", text: "Think of something you would like to return to. Choose one small step that fits today's time and energy. Finish with a final look at the tree." },
    ],
    reflection: "What became possible when you allowed an adjustment?",
    principles: "Adaptability, acceptance, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/fraxinus-pennsylvanica/",
  },
  {
    slug: "black-oak", name: "Black Oak", species: "Black oak", scientificName: "Quercus velutina",
    ...mapTreeImages["black-oak"],
    themes: ["Resolve", "Patience", "Discernment"],
    invitation: "Look carefully before naming. Let a clear intention have time to develop.",
    introduction: "An oak's familiar outline can invite a quick conclusion. Slow down beside this particular tree. Notice a leaf edge, a trunk pattern, or a branch junction, allowing details to sharpen your first impression.",
    identity: [
      { title: "Leaves and buds", text: "Alternate leaves have bristle-tipped lobes. Large end buds are hairy, giving a velvety appearance. Leaf shape varies; black oak belongs to the red oak group and can hybridize with related oaks." },
      { title: "Bark and acorns", text: "Mature bark becomes dark and deeply furrowed. Acorn cups cover roughly half the nut. The yellow-orange inner bark is an identifying feature described in references; do not cut or peel bark to look for it." },
      { title: "Place", text: "Black oak is native to eastern and central North America, often on upland slopes and ridges. Acorns support wildlife. Compare several features with a local oak identification guide." },
    ],
    seasons: "Spring brings catkins and unfolding leaves. Summer offers a fuller view of the lobes and developing acorns. Autumn foliage may be yellow-brown or dull red. Winter reveals the buds, branching, and mature bark; young trunks can look different.",
    energies: [
      { title: "Resolve", observation: "A branch junction shows several lines continuing from one trunk.", meaning: "Use the form to consider a direction you want to follow. Resolve can be a modest decision you are willing to revisit.", question: "Which intention deserves your continued effort?" },
      { title: "Patience", observation: "Some useful identifying features may be absent in the current season.", meaning: "Let an incomplete view make room for another visit. You can keep working without demanding an immediate conclusion.", question: "What would benefit from more time?" },
      { title: "Discernment", observation: "One leaf or bark pattern may resemble those of another oak.", meaning: "Practice holding an impression lightly while looking for further evidence. Careful attention can refine a confident first guess.", question: "What detail could help you judge more carefully?" },
    ],
    practiceTitle: "Give a clear intention time.",
    practiceIntroduction: "An original five-minute practice joining close observation with patient resolve.",
    practice: [
      { title: "Settle where you can see", text: "Choose stable, permitted ground and a comfortable seat or stance. Keep clear of damaged branches and falling acorns. A view from a path is enough." },
      { title: "Separate seeing from naming", text: "Describe a visible edge, color, or texture. Then notice any name or interpretation you have added. Allow the description to stand on its own for a moment." },
      { title: "Find one direction", text: "Bring a worthwhile intention to mind. Name why it matters in a simple sentence, letting your breathing continue at its ordinary pace." },
      { title: "Make a patient commitment", text: "Choose a small action and a realistic time to do it. Leave room to learn more as you go. Return your attention to the tree before finishing." },
    ],
    reflection: "What could you pursue with both resolve and patience?",
    principles: "Perseverance, one-pointed focus, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/quercus-velutina/",
  },
  {
    slug: "sweetgum", name: "Sweetgum", species: "Sweetgum", scientificName: "Liquidambar styraciflua",
    ...mapTreeImages.sweetgum,
    themes: ["Change", "Complexity", "Attention"],
    invitation: "Begin with one point. Let a complicated scene become something you can observe.",
    introduction: "A star-shaped leaf or a textured seed head offers many edges to follow. Choose one detail, then widen your view. You can appreciate complexity without having to understand every part at once.",
    identity: [
      { title: "Leaves", text: "Simple, alternate leaves usually have five to seven pointed lobes, creating a star shape, with finely toothed margins. Maples have opposite leaves; check their arrangement on a twig." },
      { title: "Fruit and branches", text: "Round, spiky fruit clusters often remain after leaves fall. Some branches develop corky wings. Fallen seed heads can make footing uneven; observe them where they lie." },
      { title: "Place", text: "Native to the eastern and central United States and farther south into Central America, sweetgum grows in moist woods and is planted in landscapes. It belongs to the Altingiaceae family." },
    ],
    seasons: "Spring brings new leaves and inconspicuous flowers. Green fruit clusters develop through summer. Autumn can combine yellow, orange, red, and purple foliage. Winter reveals branching and persistent brown seed heads; color and timing vary among trees and places.",
    energies: [
      { title: "Change", observation: "The foliage or seed heads show one stage of a seasonal cycle.", meaning: "Let the current stage prompt a description of a change in your own life. You can acknowledge its shape before deciding what to do.", question: "What is changing, and what can you name clearly?" },
      { title: "Complexity", observation: "One leaf or fruit cluster has many points and spaces.", meaning: "Use its structure as a prompt to approach a complicated matter one part at a time. You need not flatten it into a single easy explanation.", question: "Which small part could you understand next?" },
      { title: "Attention", observation: "One edge becomes distinct when you choose to follow it.", meaning: "Practice choosing a manageable focus, then allowing the wider scene back in. Attention can move between detail and context.", question: "Where would a smaller focus help?" },
    ],
    practiceTitle: "One point in a changing scene.",
    practiceIntroduction: "An original five-minute practice for meeting change and complexity through a manageable focus.",
    practice: [
      { title: "Choose even ground", text: "Sit or stand comfortably in a permitted place with clear footing. Avoid rolling seed heads underfoot. Keep living leaves and fruit attached." },
      { title: "Follow one outline", text: "Choose a leaf, seed head, or branch you can see without strain. Follow one part of its outline with your eyes while breathing naturally." },
      { title: "Widen the frame", text: "Include the branch, neighboring leaves, or surrounding space. Notice how the small detail belongs to a larger scene. Nothing needs to be solved." },
      { title: "Take one part forward", text: "Think of a complicated task or change. Name one question or action small enough to approach today. Let the remaining parts wait while you finish your visit." },
    ],
    reflection: "What felt more manageable when you began with one part?",
    principles: "One-pointed focus, adaptability, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/liquidambar-styraciflua/",
  },
  {
    slug: "bur-oak", name: "Bur Oak", species: "Bur oak", scientificName: "Quercus macrocarpa",
    ...mapTreeImages["bur-oak"],
    themes: ["Endurance", "Spaciousness", "Support"],
    invitation: "Take in a wider view. Make room for an effort you can sustain.",
    introduction: "Begin at a distance that lets you meet the tree comfortably. A broad crown or a small leaf can each hold your attention. Let the space around the tree be part of what you notice.",
    identity: [
      { title: "Leaves", text: "Alternate leaves have rounded lobes, often with a narrow middle and a broader upper section. Bur oak belongs to the white oak group. Compare several leaves; size and lobing vary." },
      { title: "Acorns and bark", text: "Large acorns have substantial cups with a conspicuous fringed rim, giving the bur or mossy appearance behind the name. Older bark is deeply furrowed. Leave bark and developing acorns attached." },
      { title: "Place", text: "Native to central and eastern North America, bur oak occurs in open landscapes and bottomlands. Established trees tolerate dry conditions as well as a range of soils. Acorns feed many wildlife species." },
    ],
    seasons: "Spring brings catkins and unfolding leaves. Summer shows the crown and developing acorns, which ripen later in the growing season. Autumn foliage is often muted. Winter offers a wider view of the branch structure and bark; every tree has its own outline.",
    energies: [
      { title: "Endurance", observation: "The trunk and branches carry a visible pattern of continued growth.", meaning: "Let the form prompt a sustainable view of your own effort. Endurance can include rest and a pace suited to your circumstances.", question: "What pace would let you continue?" },
      { title: "Spaciousness", observation: "Openings between branches are as visible as the branches themselves.", meaning: "Use those spaces as a reminder to leave room around an intention. A commitment may develop more comfortably when every moment is not filled.", question: "Where could you leave a little room?" },
      { title: "Support", observation: "A wide view includes the ground and the tree's surroundings.", meaning: "Consider the conditions that help you sustain an effort. Support may be something you can ask for, accept, or arrange.", question: "What would help carry your next step?" },
    ],
    practiceTitle: "Make room to continue.",
    practiceIntroduction: "An original five-minute practice in endurance and spaciousness, with a wide view and a sustainable next step.",
    practice: [
      { title: "Take a comfortable distance", text: "Choose stable, permitted ground away from damaged limbs and falling acorns. Sit or stand with your usual supports. A broad view from the path is welcome." },
      { title: "Notice a branch and a space", text: "Rest your eyes on one branch, then on an opening beside it. Let both belong to your view without reaching or changing your breathing." },
      { title: "Check your pace", text: "Bring one continuing effort to mind. Notice whether its current pace allows rest, support, and ordinary needs. Describe one adjustment that could help." },
      { title: "Leave room for the next visit", text: "Choose one sustainable action rather than filling every available moment. Take in the wider scene once more, then finish at your own pace." },
    ],
    reflection: "What room would help you sustain something worthwhile?",
    principles: "Perseverance, balance and optimization, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/quercus-macrocarpa/",
  },
];
