import type { Tree } from "./trees";
import { treeImages } from "./tree-images";

export const additionalTrees: readonly Tree[] = [
  {
    slug: "red-maple", name: "Red Maple", species: "Red maple", scientificName: "Acer rubrum",
    ...treeImages["red-maple"],
    themes: ["Adaptability", "Responsiveness", "Possibility"],
    invitation: "Meet the conditions you have. Notice how a small adjustment can open another way forward.",
    introduction: "Look beyond autumn color. A red maple can introduce itself through a twig, an emerging leaf, or paired winged fruits. Choose one visible detail and let your understanding of this particular tree develop across visits.",
    identity: [
      { title: "Leaves", text: "Leaves grow in opposite pairs and usually have three to five pointed lobes with toothed edges. Sugar maple leaves have smoother margins; use several features rather than autumn color alone." },
      { title: "Bark and fruits", text: "Young bark is gray and smooth; older trunks develop ridges and plates. Paired winged fruits, called samaras, mature in spring or early summer. Their color varies." },
      { title: "Place", text: "Native to eastern North America, red maple grows in a wide range of settings, including moist lowlands and upland forests. Observe the actual ground and neighboring plants without assuming every maple grows in the same conditions." },
    ],
    seasons: "Look for flower clusters before the leaves, then emerging foliage and winged fruits. Autumn can bring red, orange, or yellow. In winter, follow opposite twigs and buds. Timing varies with location and weather; a tree need not be red to be red maple.",
    energies: [
      { title: "Adaptability", observation: "Red maple occurs in varied landscapes; the tree before you has grown within one particular setting.", meaning: "Consider an adjustment that fits your own circumstances. Adaptability can begin with noticing conditions accurately.", question: "What small adjustment would help today?" },
      { title: "Responsiveness", observation: "Buds, flowers, fruits, and leaves become visible at different moments in the year.", meaning: "Let your next action respond to what is present, rather than to an old picture of how things should be.", question: "What is asking for your attention now?" },
      { title: "Possibility", observation: "Paired wings give each samara a shape quite different from the leaf beside it.", meaning: "An unfamiliar detail can suggest an unfamiliar approach. You can explore without deciding the outcome in advance.", question: "What other approach could you try?" },
    ],
    practiceTitle: "One detail. One adjustment.",
    practiceIntroduction: "A new five-minute observation practice connecting adaptability with an encounter beside red maple. Read the steps once, then look away from the screen.",
    practice: [
      { title: "Meet today's conditions", text: "Choose a permitted, comfortable viewpoint on stable ground. Notice the light, weather, and your own position. Sit or stand with your usual supports." },
      { title: "Find what is present", text: "Look for a leaf, twig, bud, or fruit you can see without reaching or picking. Describe its shape before giving it a meaning." },
      { title: "Adjust your attention", text: "If your chosen detail is hard to see, choose another. Notice that changing your approach can be part of staying with the practice." },
      { title: "Carry one response", text: "Let your breathing remain natural. After a few minutes, name one small adjustment that would make your day more workable, then finish at your own pace." },
    ],
    reflection: "What changed when you responded to the conditions you actually had?",
    principles: "Adaptability, acceptance, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/acer-rubrum/",
  },
  {
    slug: "red-oak", name: "Red Oak", species: "Northern red oak", scientificName: "Quercus rubra",
    ...treeImages["red-oak"],
    themes: ["Strength", "Spaciousness", "Stewardship"],
    invitation: "Find a steady center. Leave room for the many lives and possibilities around it.",
    introduction: "Northern red oak offers a different encounter from white oak. Look at the pointed leaf lobes, the shape of the crown, and the space beneath its branches. A tree's scale can invite reflection without requiring you to match it.",
    identity: [
      { title: "Leaves", text: "Northern red oak leaves usually have seven to eleven lobes ending in bristle tips. White oak has rounded lobes. Other red-oak-group species also have bristles, so this feature alone does not establish the species." },
      { title: "Bark and acorns", text: "Mature gray bark develops broad ridges. The acorn has a shallow, saucer-like cap covering roughly a quarter of the nut. Look at naturally fallen material and leave it in place." },
      { title: "Place", text: "Native to eastern North America, northern red oak occurs in forests and planted landscapes. A woodland tree may have a narrower crown than an open-grown individual." },
    ],
    seasons: "Spring brings new leaves and catkins; summer fills the crown. Acorns ripen in autumn, and leaves may turn russet or red before falling. Winter makes branching easier to see. Acorn production varies, so the absence of fruit on a visit is not a complete identification test.",
    energies: [
      { title: "Strength", observation: "A substantial trunk supports branches extending in several directions.", meaning: "Explore a form of strength that supports a useful action. You do not need to become rigid to remain dependable.", question: "What would steady support look like today?" },
      { title: "Spaciousness", observation: "Openings between branches remain visible even within a large crown.", meaning: "Let attention include the spaces as well as the structures. A full life can still need room for rest or a new thought.", question: "Where could you leave a little space?" },
      { title: "Stewardship", observation: "An acorn on the ground belongs to the tree's surroundings and the animals that use them.", meaning: "Consider care as an action that leaves something available for others. Looking closely does not require possession.", question: "What could you care for by leaving it undisturbed?" },
    ],
    practiceTitle: "Steady center. Open branches.",
    practiceIntroduction: "A new observation practice exploring strength and spaciousness beside northern red oak. The tree remains a subject of attention, without bearing your weight.",
    practice: [
      { title: "Settle into support", text: "Choose firm ground and a permitted viewpoint away from hazardous branches. Sit or stand with your usual supports and notice the surface beneath you." },
      { title: "Follow one branch", text: "Let your eyes travel from the trunk along one visible branch. Stop wherever the view is comfortable; there is no need to crane your neck." },
      { title: "Notice the openings", text: "Look at a patch of sky or light between branches. Let your attention include both the branch and the space beside it, with natural breathing." },
      { title: "Choose room to grow", text: "Ask where steadiness would help your day and where more room would help. Choose one modest action, then allow the visit to end." },
    ],
    reflection: "Where do you need support, and where do you need space?",
    principles: "Strength, balance and optimization, and unconditional love",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/quercus-rubra/",
  },
  {
    slug: "yellow-birch", name: "Yellow Birch", species: "Yellow birch", scientificName: "Betula alleghaniensis",
    ...treeImages["yellow-birch"],
    themes: ["Continuity", "Renewal", "Curiosity"],
    invitation: "Let a closer look deepen what you know. Follow a small detail without needing to uncover everything.",
    introduction: "Yellow birch invites attention to texture and time. Its bark can show fine curls on younger surfaces and rougher plates on older trunks. Meet those differences as they appear, leaving every layer attached.",
    identity: [
      { title: "Bark", text: "Younger trunks often show shiny yellow-bronze or silvery bark with thin horizontal curls. Older bark becomes darker and scaly. This differs from paper birch's familiar white bark; age changes both species' appearance." },
      { title: "Leaves and seed structures", text: "Alternate leaves have pointed tips and doubly toothed edges. Catkins appear in spring; upright, compact seed-bearing structures develop later. Compare bark, leaves, and twigs together." },
      { title: "Place", text: "Yellow birch is native to eastern North America and is associated with cool, moist forests. Observe from a stable path; a moist forest floor is not automatically a suitable place to stand." },
    ],
    seasons: "Look for unfolding leaves and catkins in spring, green foliage in summer, and yellow leaves in autumn. Winter reveals more bark and twig structure. A curl you notice today may look different in another light; leave the bark intact and return to observe it again.",
    energies: [
      { title: "Continuity", observation: "Several bark textures can be visible on the same tree.", meaning: "Let earlier and newer parts of your experience belong to one life. You can keep what is useful while learning something new.", question: "What would you like to carry forward?" },
      { title: "Renewal", observation: "Fine curls and exposed surfaces create a changing pattern on younger bark.", meaning: "Treat renewal as something to notice, not something to force. A new beginning can coexist with an established commitment.", question: "What is quietly taking a new form?" },
      { title: "Curiosity", observation: "A close view of bark reveals details that are difficult to see from a distance.", meaning: "Ask a more precise question before reaching a conclusion. Familiarity can be the beginning of inquiry.", question: "What have you not yet noticed?" },
    ],
    practiceTitle: "Look closer. Leave the layers.",
    practiceIntroduction: "A new five-minute practice of observation and reflection beside yellow birch, connecting curiosity with presence and care.",
    practice: [
      { title: "Choose a view", text: "Find a permitted place on firm ground where you can see the trunk comfortably. Use your usual seat or standing supports. A distant view is enough." },
      { title: "Describe three details", text: "Notice a color, a line, and a texture. Keep bark attached; do not peel or scratch it to discover what lies underneath." },
      { title: "Look again", text: "Return to your first detail and notice whether the light changes your description. Let your breathing remain natural and your interpretation stay open." },
      { title: "Keep one question", text: "Consider something familiar in your day. Choose a question that could help you see it more clearly, then finish the visit without needing an answer." },
    ],
    reflection: "What did a closer look add to something you thought you knew?",
    principles: "Presence, adaptability, and perseverance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/betula-alleghaniensis/",
  },
  {
    slug: "balsam-fir", name: "Balsam Fir", species: "Balsam fir", scientificName: "Abies balsamea",
    ...treeImages["balsam-fir"],
    themes: ["Stillness", "Attention", "Gentleness"],
    invitation: "Allow a quiet encounter. Give one small detail your attention without asking it to change your mood.",
    introduction: "Balsam fir is a northern evergreen with much to notice at a small scale. A visible twig, the underside of a fallen needle, or the outline of a crown can be enough for a visit. Let the tree's presence come before an expectation of calm.",
    identity: [
      { title: "Needles", text: "Flat needles grow singly along twigs and usually have rounded or slightly notched tips. Two pale bands appear underneath. Spruce needles are more angular; compare several features without pulling needles from a living branch." },
      { title: "Bark and cones", text: "Young bark is smooth and gray with resin blisters; older bark becomes rougher. Seed cones stand upright near the upper crown and break apart on the tree, so intact fallen cones are not usually available." },
      { title: "Place", text: "Native to northern North America, balsam fir occurs in cool forests. Its usually narrow, conical outline can differ with age, wind exposure, and growing conditions." },
    ],
    seasons: "Green needles remain through winter while individual needles are eventually replaced. Notice fresh growth, cone development when visible, and changing light around the crown. Do not puncture resin blisters or crush foliage to seek a scent; visual observation is enough.",
    energies: [
      { title: "Stillness", observation: "An evergreen crown remains a visible form even when surrounding deciduous trees are bare.", meaning: "Explore pausing within changing circumstances. Stillness can be a brief choice, without requiring a quiet mind.", question: "Where could you allow a small pause?" },
      { title: "Attention", observation: "A needle's upper and lower surfaces have different appearances.", meaning: "Let one detail reveal more than your first glance. Attention can deepen without becoming effortful.", question: "What deserves a second look?" },
      { title: "Gentleness", observation: "Young bark carries resin blisters that can be observed without touching them.", meaning: "Consider an approach that learns without pressing or taking. Care can be quiet and specific.", question: "What would a gentler approach change?" },
    ],
    practiceTitle: "A quiet point of attention.",
    practiceIntroduction: "A new observation meditation beside balsam fir, connecting one-pointed focus with a gentle way of returning attention.",
    practice: [
      { title: "Arrive without a demand", text: "Choose a safe, permitted viewpoint with your usual supports. Allow your present mood to be part of the visit; no particular feeling is required." },
      { title: "Choose one quiet detail", text: "Rest your gaze on a twig, a patch of bark, or the crown's outline. Keep eyes open and breathe naturally." },
      { title: "Return gently", text: "When a sound or thought draws your attention away, notice it and return to the detail. Change your position or anchor whenever comfort requires it." },
      { title: "Let the pause finish", text: "Widen your attention to the surrounding forest or landscape. Carry one gentle intention into your next activity, then end at your own pace." },
    ],
    reflection: "What was it like to pay attention without demanding a particular feeling?",
    principles: "One-pointed focus, acceptance, and unconditional love",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/abies-balsamea/",
  },
  {
    slug: "tamarack", name: "Tamarack", species: "Tamarack", scientificName: "Larix laricina",
    ...treeImages["tamarack"],
    themes: ["Change", "Release", "Return"],
    invitation: "Notice what a season asks you to keep and what it asks you to let go. Leave room for another return.",
    introduction: "A conifer need not remain green through winter. Tamarack turns gold and sheds its needles, offering a striking encounter with seasonal change. Begin with the tree you find today, whether green, golden, or bare.",
    identity: [
      { title: "Needles", text: "Soft, short needles occur in clusters on short shoots and singly on new long shoots. They turn yellow before falling in autumn. Other larches share this habit; needle loss alone does not identify tamarack." },
      { title: "Cones and bark", text: "Small, upright seed cones ripen brown and may remain attached after releasing seeds. Bark becomes reddish brown and scaly with age. Observe accessible details without picking cones or removing bark." },
      { title: "Place", text: "Native across northern North America, tamarack often grows in bogs and other wet settings, but also occurs on upland sites. Use a permitted boardwalk or stable viewpoint rather than entering wet ground for a closer look." },
    ],
    seasons: "Fresh green needles emerge in spring, fill the branches in summer, and turn golden before autumn shedding. Winter exposes the fine branching and retained cones. Local conditions affect timing. Bare winter branches are part of this deciduous conifer's normal annual cycle.",
    energies: [
      { title: "Change", observation: "The same crown can be green, golden, or bare at different times of year.", meaning: "Let a change be visible before deciding whether it is good or bad. Different seasons can ask for different ways of participating.", question: "What season are you meeting in your own life?" },
      { title: "Release", observation: "Needles fall while the tree's branching structure remains.", meaning: "Consider one demand or habit you could set down while keeping what matters. Release can be selective and practical.", question: "What could you put down for now?" },
      { title: "Return", observation: "New needles emerge after a bare winter.", meaning: "Reflect on a practice you can return to when conditions allow. A pause does not have to erase a commitment.", question: "What would you like to return to in time?" },
    ],
    practiceTitle: "Keep. Release. Return.",
    practiceIntroduction: "A new five-minute contemplation beside tamarack, using its visible seasonal form as a starting point for exploring release and perseverance.",
    practice: [
      { title: "Meet the current form", text: "Choose a stable, permitted viewpoint with your usual supports. Name what you actually see: green needles, gold, bare twigs, cones, or another detail." },
      { title: "Find what remains", text: "Follow one visible branch. Notice the structure beneath today's foliage, without assuming every loss or change has the same meaning." },
      { title: "Consider one release", text: "With natural breathing, ask whether there is one unnecessary demand you could set down today. Let the question stay modest; no major decision is needed." },
      { title: "Choose a return", text: "Name something worthwhile you would like to revisit, whether this tree or a practice in your day. Finish without making a deadline or a streak." },
    ],
    reflection: "What can you release while remaining connected to what matters?",
    principles: "Release, adaptability, and perseverance",
    sourceUrl: "https://research.fs.usda.gov/silvics/tamarack",
    sourceLabel: "US Forest Service's Tamarack profile",
  },
  {
    slug: "sycamore", name: "Sycamore", species: "American sycamore", scientificName: "Platanus occidentalis",
    ...treeImages["sycamore"],
    themes: ["Perspective", "Individuality", "Connection"],
    invitation: "Look at the pattern, then widen your view. Notice how a distinctive life belongs to a larger place.",
    introduction: "American sycamore can catch your eye from far away with pale upper bark and a spreading crown. Closer attention reveals a mosaic of colors and textures. Let both distances have a place in the encounter.",
    identity: [
      { title: "Bark", text: "Upper bark sheds in patches, revealing pale cream or white surfaces among gray and brown. The lower trunk may be darker and scaly. Leave attached bark in place." },
      { title: "Leaves and fruits", text: "Large, alternate leaves have three to five main lobes and coarse teeth. Round seed balls hang on slender stalks, usually singly. London plane can look similar, so compare several features." },
      { title: "Place", text: "Native to eastern and central North America, American sycamore often grows near rivers and streams and is also planted in parks. Observe from stable ground rather than stepping onto an eroding bank." },
    ],
    seasons: "Broad leaves fill the crown in summer, then turn yellow or brown in autumn. Winter reveals pale branches and hanging seed balls. Look for new foliage in spring. The bark's pattern and the tree's surroundings can reward attention in any season.",
    energies: [
      { title: "Perspective", observation: "From a distance the trunk may look pale; nearer views reveal separate patches and edges.", meaning: "A different viewpoint can change what you notice without making the earlier view worthless. Consider both detail and context.", question: "What would a wider view help you understand?" },
      { title: "Individuality", observation: "The arrangement of bark patches differs along the trunk and between trees.", meaning: "Notice a particular life rather than only its category. Your own experience also contains details that a label cannot capture.", question: "What detail makes this encounter particular?" },
      { title: "Connection", observation: "A spreading crown shares its setting with light, neighboring plants, and passing animals.", meaning: "Consider how your distinct contribution participates in a wider place. Individuality and connection can grow together.", question: "What are you part of today?" },
    ],
    practiceTitle: "A detail and a wider world.",
    practiceIntroduction: "A new observation practice beside American sycamore, moving attention between one bark detail and its surrounding landscape.",
    practice: [
      { title: "Find a comfortable view", text: "Choose a permitted place on firm ground, clear of hazardous branches. Sit or stand with your usual supports; you can explore both scales from one position." },
      { title: "Notice one patch", text: "Choose a visible bark patch. Describe its color, edge, and neighboring texture without touching or peeling it." },
      { title: "Widen your attention", text: "Let your gaze include the trunk, then the crown and surrounding place. Keep your neck comfortable and breathing natural. Notice what the close view left out." },
      { title: "Bring both views along", text: "Think of one situation in your day that might benefit from attention to detail and context. Choose a useful question, then finish the visit." },
    ],
    reflection: "What did the wider view reveal, and what did the small detail preserve?",
    principles: "Presence, balance and optimization, and unconditional love",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/platanus-occidentalis/",
  },
];
