import type { Tree } from "./trees";
import { growthTreeImages } from "./tree-library-growth-images";

export const growthPracticeTrees: readonly Tree[] = [
  {
    slug: "american-hophornbeam", name: "American Hophornbeam", species: "American hophornbeam", scientificName: "Ostrya virginiana",
    ...growthTreeImages["american-hophornbeam"],
    themes: ["Quiet Endurance", "Patience", "Attention"],
    invitation: "Notice a small tree's presence. Find a pace you can return to.",
    introduction: "You can meet this tree without searching for a spectacular specimen. Begin with one visible detail and allow an ordinary encounter to hold your attention.",
    identity: [
      { title: "Bark and comparison", text: "Mature hophornbeam has gray-brown bark broken into narrow, loose scales. American hornbeam (Carpinus caroliniana) instead has a smooth, fluted, muscular-looking trunk. Both are sometimes called ironwood; compare several features." },
      { title: "Leaves and fruit", text: "Alternate, simple leaves have doubly toothed edges. Clusters of inflated, papery sacs enclose small nutlets and resemble hops. American hornbeam has leafy, three-lobed fruit bracts instead." },
      { title: "Place", text: "This slow-growing member of the birch family occurs in eastern North American woods, including dry slopes and well-drained sites. It often grows beneath larger trees." },
    ],
    seasons: "Look for hanging male catkins in winter and spring, leafy crowns in summer, and hop-like fruit clusters later in the year. Autumn leaves may turn yellow. Young bark can appear smoother than mature bark.",
    energies: [
      { title: "Quiet Endurance", observation: "A small trunk can be easy to pass without noticing.", meaning: "Let this encounter bring an overlooked effort to mind. Continuing can take a modest, repeatable form.", question: "What quiet effort deserves recognition?" },
      { title: "Patience", observation: "A few minutes of looking reveal texture, but cannot show a season of growth.", meaning: "Give an ongoing effort room to develop beyond today's view. Choose a timescale that fits the work.", question: "What would a sustainable pace feel like?" },
      { title: "Attention", observation: "Similar common names can belong to trees with different bark and fruit.", meaning: "Let curiosity make your first impression more precise. Looking again is part of learning.", question: "What detail changes your understanding?" },
    ],
    practiceTitle: "Find your steady pace.",
    practiceIntroduction: "An original five-minute observation practice exploring quiet endurance and a manageable next step.",
    practice: [
      { title: "Settle where you are", text: "Choose stable, permitted ground. Sit or stand with your usual supports, at a distance that makes looking comfortable. Let your breath follow its natural rhythm." },
      { title: "Find one small detail", text: "Rest your eyes on a patch of bark, a leaf edge, or a branch. Notice its shape without removing anything. A clear view from the path is enough." },
      { title: "Return gently", text: "When your attention moves elsewhere, return to that detail. Repeat a few times, allowing each return to be simple." },
      { title: "Choose a repeatable step", text: "Think of one effort you want to continue. Choose a small action you could realistically repeat, then finish with another look at the tree." },
    ],
    reflection: "What could you continue with a little more patience and a little less strain?",
    principles: "Perseverance, presence, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/ostrya-virginiana/",
  },
  {
    slug: "river-birch", name: "River Birch", species: "River birch", scientificName: "Betula nigra",
    ...growthTreeImages["river-birch"],
    themes: ["Adaptability", "Change", "Presence"],
    invitation: "Follow a changing surface. Make room for one useful adjustment.",
    introduction: "Light catches the bark differently from one moment to the next. Let the tree before you be a place to notice change without needing to make anything happen.",
    identity: [
      { title: "Bark", text: "Salmon, cinnamon, and brown tones appear in peeling bark layers. Older trunks can become darker and ridged. Leave peeling bark attached; color and texture vary with age and cultivar." },
      { title: "Leaves", text: "Simple, alternate leaves are roughly diamond-shaped to oval, with pointed tips and doubly toothed edges. Use leaves, bark, and setting together when distinguishing birches." },
      { title: "Place", text: "Native to the central and eastern United States, river birch grows along waterways and floodplains and is also planted in landscapes. It tolerates wet conditions and more heat than many other birches." },
    ],
    seasons: "Spring brings catkins and new leaves, followed by small seeds in late spring or early summer. Leaves may yellow in autumn; bark remains visible through winter. Dry summer conditions can cause some leaves to fall early.",
    energies: [
      { title: "Adaptability", observation: "Different patches of bark offer different colors and textures.", meaning: "Use that variety as a prompt to consider more than one workable response. An adjustment can be small.", question: "What could you adjust to meet today's conditions?" },
      { title: "Change", observation: "The tree's appearance shifts with light, weather, and season.", meaning: "Give yourself time to notice what has changed before deciding how to respond.", question: "What is different now from your last visit?" },
      { title: "Presence", observation: "One visible edge offers a place to rest your attention.", meaning: "Bring your attention to what is available here. You can meet this moment at your own pace.", question: "What can you notice without trying to alter it?" },
    ],
    practiceTitle: "Notice change. Find your footing.",
    practiceIntroduction: "An original five-minute practice connecting close observation with a flexible response to change.",
    practice: [
      { title: "Choose steady ground", text: "Stay on a stable, permitted path away from steep or slippery banks. Sit or stand comfortably with your usual supports; a planted river birch works just as well." },
      { title: "Look at two textures", text: "Find two patches of bark or two parts of the canopy. Let your eyes move between them. Keep all bark and leaves attached." },
      { title: "Notice your response", text: "Bring a recent change to mind. Notice your first response without needing to settle it. Keep breathing naturally and return your gaze to the tree whenever useful." },
      { title: "Allow one adjustment", text: "Choose one practical adjustment that fits your present circumstances. It might be a different pace, a request for help, or a little more time." },
    ],
    reflection: "Which small adjustment would help you meet what is changing?",
    principles: "Acceptance, presence, and balance and optimization",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/betula-nigra/",
  },
  {
    slug: "black-walnut", name: "Black Walnut", species: "Black walnut", scientificName: "Juglans nigra",
    ...growthTreeImages["black-walnut"],
    themes: ["Patience", "Long-term Growth", "Care"],
    invitation: "Look beyond today's result. Choose something worth tending over time.",
    introduction: "A crown of branches can invite a longer view of your own work. Meet the individual tree first, then consider what you are willing to give time and care.",
    identity: [
      { title: "Leaves", text: "Alternate, compound leaves carry many toothed leaflets along a central stalk. The terminal leaflet may be small or absent. Compare the whole leaf and twig, rather than treating a leaflet as a complete leaf." },
      { title: "Bark and fruit", text: "Dark bark develops deep furrows. Round nuts grow inside thick green husks that darken and can stain. Observe fallen fruit in place and choose a viewpoint clear of falling nuts." },
      { title: "Place", text: "A large member of the walnut family native to central and eastern North America, black walnut often grows in fertile, well-drained soils. Its nuts provide food for squirrels and other wildlife." },
    ],
    seasons: "Look for fresh compound leaves and catkins in spring, a full canopy in summer, and ripening nuts with yellowing foliage in autumn. Winter reveals branch structure and furrowed bark. Nut crops vary between years.",
    energies: [
      { title: "Patience", observation: "A single visit gives a brief view of a living tree.", meaning: "Let the limited view remind you to leave room for development you cannot assess today.", question: "What deserves more time before you judge its outcome?" },
      { title: "Long-term Growth", observation: "Branches divide into smaller branches across the crown.", meaning: "Use that visible structure as a metaphor for a larger effort made of many small choices.", question: "Which small choice supports your longer intention?" },
      { title: "Care", observation: "The ground around the tree holds leaves, twigs, and sometimes fallen fruit.", meaning: "Consider the ordinary conditions that help your own work continue. Time, rest, and practical support deserve attention.", question: "What condition could you improve this week?" },
    ],
    practiceTitle: "Tend what takes time.",
    practiceIntroduction: "An original five-minute practice for patient attention to a long-term intention.",
    practice: [
      { title: "Find a comfortable viewpoint", text: "Sit or stand on stable, permitted ground with your usual supports, clear of falling nuts and damaged branches. Observe the crown from a comfortable distance." },
      { title: "Follow one branch", text: "Trace a branch with your eyes as far as you can comfortably see. If looking upward strains your neck, choose a line in the bark instead." },
      { title: "Name a longer intention", text: "Bring one project, relationship, or skill to mind. Say quietly what you hope to care for over time, without setting a demand for today's results." },
      { title: "Choose today's care", text: "Name one manageable action that supports that intention. Give it a realistic place in your day, then return your attention to the tree before leaving." },
    ],
    reflection: "What can you tend today even when the result is still far away?",
    principles: "Perseverance, presence, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/juglans-nigra/",
  },
  {
    slug: "american-basswood", name: "American Basswood", species: "American basswood", scientificName: "Tilia americana",
    ...growthTreeImages["american-basswood"],
    themes: ["Connection", "Generosity", "Reciprocity"],
    invitation: "Notice the life around a tree. Consider what you receive and what you can offer.",
    introduction: "Begin with the whole scene: tree, light, surrounding plants, and any movement you can see or hear. Let the encounter invite curiosity about your own connections.",
    identity: [
      { title: "Leaves", text: "Large, alternate leaves have toothed margins, pointed tips, and a heart-shaped base that is often uneven. Other lindens can look similar, so check more than leaf shape." },
      { title: "Flowers and fruit", text: "Clusters of small, pale yellow flowers hang from a stalk joined to a narrow, leaflike bract. Small nutlets later accompany these bracts. Flowers attract bees and other pollinators." },
      { title: "Place", text: "Also called American linden, this large eastern North American shade tree belongs to the mallow family. It commonly grows in moist, fertile, well-drained woods. Older bark becomes furrowed." },
    ],
    seasons: "Watch leaves unfold in spring and flowers open in late spring or summer, depending on location. Later, look for nutlets and their bracts. Autumn foliage can become pale yellow; winter exposes the branching crown.",
    energies: [
      { title: "Connection", observation: "A tree shares the scene with other plants and passing animals.", meaning: "Let the wider view bring your own relationships into awareness. Connection can begin with noticing who is already present.", question: "Which connection would you like to attend to?" },
      { title: "Generosity", observation: "The canopy creates a patch of shade as the sun moves.", meaning: "Use that shelter as a prompt to consider an offer that fits your capacity. A small act can be enough.", question: "What could you offer freely and sustainably?" },
      { title: "Reciprocity", observation: "During flowering, insects may move between the blooms.", meaning: "Consider both giving and receiving in your own life. Leave room to recognize help and to accept it.", question: "What have you received that you could acknowledge?" },
    ],
    practiceTitle: "Receive. Notice. Offer.",
    practiceIntroduction: "An original five-minute practice exploring connection and generosity through the life around a tree.",
    practice: [
      { title: "Settle at an easy distance", text: "Choose stable, permitted ground. Sit or stand with your usual supports. Give flower-visiting insects space and observe from farther away if that is more comfortable." },
      { title: "Widen your attention", text: "Notice the tree and then its surroundings: light, shade, nearby plants, or movement. Listen if useful; seeing alone is enough, and quiet is welcome too." },
      { title: "Recognize what you receive", text: "Bring one source of support to mind. Name it simply. Allow yourself a moment to appreciate receiving without immediately needing to repay it." },
      { title: "Choose a fitting offer", text: "Think of one manageable act of care or generosity. Choose something within your capacity, then leave the tree and surrounding life undisturbed." },
    ],
    reflection: "What connection could you nourish with one small, sustainable act?",
    principles: "Presence, gratitude, and learning from trees",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/tilia-americana/",
  },
];
