import type { Tree } from "./trees";
import { expansionImages } from "./tree-expansion-images";

export const tennesseeTrees: readonly Tree[] = [
  {
    slug: "tulip-tree", name: "Tulip Tree", species: "Tulip tree", scientificName: "Liriodendron tulipifera",
    ...expansionImages["tulip-tree"],
    themes: ["Aspiration", "Perspective", "Wonder"],
    invitation: "Let a small detail widen your perspective. Give your next intention room to grow.",
    introduction: "Begin with what is within view: a leaf silhouette, a patch of light, or the shape of a branch. You do not need to see the whole crown to make a meaningful encounter. One clear observation can be enough.",
    identity: [
      { title: "Leaves", text: "Alternate leaves have four main lobes and a broad, notched or flattened tip. Their distinctive outline is a useful clue; compare the twig and other features too." },
      { title: "Flowers and fruit", text: "Greenish-yellow, cup-shaped flowers have orange markings. The cone-like fruit separates into winged seeds. Flowers may be high above a comfortable viewpoint." },
      { title: "Place", text: "Native to eastern North America, tulip tree belongs to the magnolia family. Despite the name tulip-poplar, it is not a true poplar. It often grows in moist, well-drained forest settings." },
    ],
    seasons: "Watch leaves unfold in spring and look for flowers in late spring or early summer. Leaves often turn yellow in autumn. In winter, notice the outline of branches and any remaining fruit structures; timing varies by place.",
    energies: [
      { title: "Aspiration", observation: "Follow a visible line from the trunk toward a branch.", meaning: "Use that direction as an invitation to name something worth growing toward. An aspiration can remain simple and close to everyday life.", question: "What would you like to give patient attention?" },
      { title: "Perspective", observation: "A leaf and a whole crown offer different scales of looking.", meaning: "Move between one small action and the wider purpose it serves. Neither view needs to contain everything.", question: "How does your next small step fit the larger picture?" },
      { title: "Wonder", observation: "Look for an outline you would find difficult to draw from memory.", meaning: "Let surprise interrupt the assumption that you already know this tree. Curiosity can begin again on a familiar path.", question: "What have you overlooked?" },
    ],
    practiceTitle: "A small detail. A wider view.",
    practiceIntroduction: "A new five-minute observation practice connecting aspiration with attention. Read the steps, then return your eyes to the tree.",
    practice: [
      { title: "Choose a comfortable view", text: "Sit or stand on permitted, stable ground with your usual supports. Keep your neck comfortable and your gaze at an easy height." },
      { title: "Trace one shape", text: "Follow a visible leaf edge or branch with your eyes. If it is too distant, choose a closer detail. Leave leaves and flowers attached." },
      { title: "Widen the frame", text: "Include the surrounding light and neighboring plants. Let your breath continue naturally. Notice how the detail belongs to a larger scene." },
      { title: "Name one next step", text: "Choose a modest action connected to something you care about. Finish when ready, carrying the intention with you." },
    ],
    reflection: "What became clearer when you moved between the detail and the wider view?",
    principles: "One-pointed focus and aspiration for excellence, presence, and perseverance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/liriodendron-tulipifera/",
  },
  {
    slug: "sassafras", name: "Sassafras", species: "Sassafras", scientificName: "Sassafras albidum",
    ...expansionImages.sassafras,
    themes: ["Possibility", "Acceptance", "Curiosity"],
    invitation: "Make room for more than one shape. Notice a difference without needing to resolve it.",
    introduction: "A first impression is only a beginning. Give this encounter enough time for a second detail to appear. The practice is to look carefully and allow your description to become more generous.",
    identity: [
      { title: "Leaves", text: "One sassafras can carry unlobed, mitten-shaped, and three-lobed leaves. Leaves are alternate. Not every twig will display every shape." },
      { title: "Flowers and fruit", text: "Small yellow-green flowers appear in spring. Female trees can bear blue fruits held in red cups on red stalks. Observe without tasting or collecting." },
      { title: "Place", text: "Native to eastern North America, sassafras occurs in woods, edges, and old fields. Root sprouts can form colonies. Mature bark develops furrows." },
    ],
    seasons: "Look for spring flowers, then compare summer leaf outlines. Autumn foliage can be yellow, orange, or red. Winter offers buds, branches, and bark to observe when leaf shapes are absent.",
    energies: [
      { title: "Possibility", observation: "Different leaf outlines may be visible on the same tree.", meaning: "Let variation suggest that there may be several workable ways to approach a situation. You need not choose immediately.", question: "What other possibility deserves a look?" },
      { title: "Acceptance", observation: "The leaf shapes before you need not match one imagined ideal.", meaning: "Practice describing a difference before judging it. Acceptance here means giving an observation room to be accurate.", question: "What can you acknowledge as it is?" },
      { title: "Curiosity", observation: "A second leaf may add something to your first impression.", meaning: "Keep an initial conclusion lightly enough that new evidence can change it.", question: "What could a second look teach you?" },
    ],
    practiceTitle: "More than one way to be.",
    practiceIntroduction: "A new observation practice exploring acceptance through comparison. About five minutes is enough; a shorter encounter is welcome.",
    practice: [
      { title: "Settle at a viewpoint", text: "Choose a permitted place and a supported position. Keep branches and roots undisturbed." },
      { title: "Describe one detail", text: "Choose a leaf, twig, or bark pattern. Silently name its outline in ordinary words. No botanical vocabulary is required." },
      { title: "Find a difference", text: "Compare another visible detail. Notice one similarity and one difference without ranking them. In winter, compare branch shapes instead." },
      { title: "Leave a question open", text: "Breathe naturally. Carry one curious question into your day and allow yourself time to learn the answer." },
    ],
    reflection: "Where did a second look make your first impression more spacious?",
    principles: "Acceptance, adaptability, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/sassafras-albidum/",
  },
  {
    slug: "blackgum", name: "Blackgum", species: "Blackgum", scientificName: "Nyssa sylvatica",
    ...expansionImages.blackgum,
    themes: ["Presence", "Patience", "Attentiveness"],
    invitation: "Stay with what is here. Let an ordinary detail earn your attention.",
    introduction: "There is no need to wait for a spectacular tree or a spectacular feeling. Begin with one patch of this tree that you can see clearly. The encounter can be quiet and still be complete.",
    identity: [
      { title: "Leaves", text: "Alternate, simple leaves are often glossy and oval, with mostly smooth margins. Leaf shape alone is not enough to distinguish blackgum from similar trees." },
      { title: "Bark and fruit", text: "Older bark can form dark, block-like plates. Small blue-black fruits may occur on fruiting trees. Look for several features together and leave fruit in place." },
      { title: "Place", text: "Also called black tupelo, Nyssa sylvatica occurs in eastern North American forests and planted landscapes. It grows in varied upland and lowland settings; it is a different species from sweetgum." },
    ],
    seasons: "Notice emerging spring foliage, summer leaf shine, and autumn color that can become vivid red. Winter makes branch outlines and bark easier to study. Color depends on the individual tree and conditions.",
    energies: [
      { title: "Presence", observation: "Light falls differently across neighboring leaves or bark surfaces.", meaning: "Let this actual pattern hold your attention for a moment, without asking it to improve your mood.", question: "What is here before you name how you feel?" },
      { title: "Patience", observation: "Some details become easier to see after you pause.", meaning: "Allow understanding to take more than one glance. You can return another day without having finished today.", question: "What might benefit from another patient visit?" },
      { title: "Attentiveness", observation: "A familiar-looking leaf still has its own edges, shadows, and position.", meaning: "Practice giving care to something you would usually pass by. Attention can be specific and modest.", question: "What ordinary thing deserves a little more care?" },
    ],
    practiceTitle: "Stay for one more detail.",
    practiceIntroduction: "A new five-minute practice in unhurried observation, connecting presence with time beside blackgum.",
    practice: [
      { title: "Arrive with support", text: "Choose a comfortable seat or stance on stable, permitted ground. Observe from a distance when that works better." },
      { title: "Choose a small area", text: "Rest your gaze on a leaf cluster, bark patch, or branch junction. Describe one visible feature to yourself." },
      { title: "Notice again", text: "Let breathing remain natural. When attention wanders, return and find one detail you did not name before. There is no target number." },
      { title: "Finish without a verdict", text: "Widen your attention and prepare to leave. A few moments of looking count, whether the encounter felt peaceful, restless, or ordinary." },
    ],
    reflection: "What did you notice after the first glance?",
    principles: "Presence, perseverance, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/nyssa-sylvatica/",
  },
  {
    slug: "dawn-redwood", name: "Dawn Redwood", species: "Dawn redwood", scientificName: "Metasequoia glyptostroboides",
    ...expansionImages["dawn-redwood"],
    themes: ["Release", "Renewal", "Balance"],
    invitation: "Notice what this season holds. Let change have a place in continuity.",
    introduction: "Meet the tree in the season you actually have. A full crown, a changing branch, or bare twigs each offer a complete starting point. Your encounter does not need to match a photograph.",
    identity: [
      { title: "Foliage", text: "Dawn redwood is a deciduous conifer. Its soft, flat needles and small branchlets are arranged oppositely; bald cypress has an alternate arrangement. Compare several features." },
      { title: "Bark and cones", text: "Look for reddish-brown, furrowed bark and small rounded cones. A mature tree can develop a broad, fluted trunk base." },
      { title: "Place", text: "Native to China, dawn redwood is planted in parks and gardens elsewhere. It is distinct from coast redwood and giant sequoia. A planted specimen can still be a place for attentive practice." },
    ],
    seasons: "Fresh foliage appears in spring. Needles turn coppery brown in autumn and fall, leaving the winter branch structure visible. Seasonal needle loss is part of this conifer's normal cycle.",
    energies: [
      { title: "Release", observation: "Autumn needle fall leaves branches with a different outline.", meaning: "Use the seasonal change as a prompt to consider one effort you could set down. This is an invitation, not a demand to let go.", question: "What could you stop carrying for today?" },
      { title: "Renewal", observation: "Return visits can reveal foliage where a winter view showed bare twigs.", meaning: "Make room for beginning again without requiring a dramatic transformation. A repeated small practice is enough.", question: "What would a gentle new beginning look like?" },
      { title: "Balance", observation: "Paired foliage offers a visible pattern to compare.", meaning: "Consider how effort and rest fit your own circumstances. Balance need not mean equal amounts at every moment.", question: "What needs a little more room in your day?" },
    ],
    practiceTitle: "Meet this season.",
    practiceIntroduction: "A new five-minute contemplation connecting release and renewal with the tree's visible seasonal condition.",
    practice: [
      { title: "Find an easy position", text: "Use a permitted viewpoint on stable ground. Sit or stand with your usual supports and leave the trunk and roots undisturbed." },
      { title: "Name the present scene", text: "Observe foliage, twigs, cones, or bark. Describe what you actually see without needing the tree to look a different way." },
      { title: "Consider one adjustment", text: "With natural breathing, ask whether today calls for a small effort, a pause, or simply continued attention. No particular answer is required." },
      { title: "Carry the season with you", text: "Choose one manageable response and end at your own pace. If useful, plan to return and notice what changes." },
    ],
    reflection: "What did meeting this season suggest about your own pace?",
    principles: "Release, adaptability, and balance and optimization",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/metasequoia-glyptostroboides/",
  },
];
