import type { Tree } from "./trees";
import { fourTreeImages } from "./tree-library-four-images";

export const fourPracticeTrees: readonly Tree[] = [
  {
    slug: "american-hornbeam", name: "American Hornbeam", species: "American hornbeam", scientificName: "Carpinus caroliniana",
    ...fourTreeImages["american-hornbeam"],
    themes: ["Quiet Strength", "Attention", "Support"],
    invitation: "Follow one curve. Notice the support that lets you soften your effort.",
    introduction: "A small tree can hold your attention as fully as a giant. Begin with the lines of its trunk, then notice the space around it. Let your encounter take its own scale.",
    identity: [
      { title: "Bark", text: "Smooth gray bark follows a fluted trunk and branches, creating the muscular appearance behind the name musclewood. American hophornbeam is a different species with rougher bark." },
      { title: "Leaves and fruit", text: "Simple, alternate leaves have toothed edges and prominent side veins. Small nutlets accompany leafy, three-lobed bracts. Compare bark, leaves, and fruit when available." },
      { title: "Place", text: "A member of the birch family native to eastern North America, American hornbeam often grows beneath taller trees in moist woods and beside streams." },
    ],
    seasons: "Look for catkins and unfolding leaves in spring. Summer reveals leaf veins and bracts; autumn may bring yellow, orange, or red. The trunk's fluted lines remain visible in winter.",
    energies: [
      { title: "Quiet Strength", observation: "Light and shade reveal the curves of a modest-sized trunk.", meaning: "Let the form prompt a question about strength in your own life. Consider the steady effort that can be easy to overlook.", question: "What quiet effort is already supporting you?" },
      { title: "Attention", observation: "One curve becomes clearer as your eyes follow its changing edge.", meaning: "Give a small part of your experience enough time to become specific. You can attend closely without tightening your whole body.", question: "Where could a little less effort make room for clearer attention?" },
      { title: "Support", observation: "The tree stands among soil, neighboring plants, and changing light.", meaning: "Use the surrounding scene as a reminder to recognize your own sources of support. Receiving help can be part of continuing.", question: "Which support could you acknowledge today?" },
    ],
    practiceTitle: "Follow the curve. Ease the effort.",
    practiceIntroduction: "An original five-minute observation practice exploring quiet strength and the support available to you.",
    practice: [
      { title: "Find your support", text: "Sit or stand comfortably on permitted, stable ground, using your usual supports. Remain on the path near streams. Let the seat or ground carry your weight." },
      { title: "Follow a curve", text: "Choose a line in the bark at an easy height. Trace it slowly with your eyes. A branch outline works too; you can stay at a distance." },
      { title: "Check your effort", text: "Notice your jaw, shoulders, or hands. If comfortable, ease one small area of tension. Keep breathing naturally and return your eyes to the curve." },
      { title: "Recognize one support", text: "Name something that helps you continue: a person, a place, a routine, or a practical tool. Choose one way to appreciate or use that support today." },
    ],
    reflection: "What became easier when you noticed what was supporting you?",
    principles: "Presence, balance and optimization, and acceptance",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/carpinus-caroliniana/",
  },
  {
    slug: "shagbark-hickory", name: "Shagbark Hickory", species: "Shagbark hickory", scientificName: "Carya ovata",
    ...fourTreeImages["shagbark-hickory"],
    themes: ["Patience", "Continuity", "Care"],
    invitation: "Let the layers hold your attention. Give something worthwhile time to develop.",
    introduction: "Some encounters begin with an unmistakable texture. Others begin with a young trunk whose familiar features have yet to develop. Meet the tree before you in its present stage.",
    identity: [
      { title: "Bark", text: "Older trunks develop long strips of bark that lift away at their ends. Young trees can have smoother bark. Leave loose-looking strips attached." },
      { title: "Leaves and nuts", text: "Alternate, compound leaves usually have five leaflets, sometimes seven. The nuts sit inside thick husks that divide into four sections. Use several features to distinguish hickories." },
      { title: "Place", text: "Shagbark hickory belongs to the walnut family and is native across much of eastern and central North America. It occurs in woodlands and provides food for wildlife." },
    ],
    seasons: "Spring brings unfolding compound leaves and flowers. Watch the full canopy in summer, then yellow foliage and ripening nuts in autumn. Winter offers clear views of bark and buds; mature shaggy bark is not present on every tree.",
    energies: [
      { title: "Patience", observation: "The bark on a young tree may differ from the mature form in a photograph.", meaning: "Let an unfinished appearance prompt patience with something still developing in your life. Name the stage you are actually in.", question: "What are you asking to be finished before it has had time?" },
      { title: "Continuity", observation: "Attached bark strips create overlapping lines along the trunk.", meaning: "Use the visible layers as a metaphor for experience carried forward. You can recognize earlier work while making room for a next step.", question: "Which earlier effort can you build on?" },
      { title: "Care", observation: "Details can be observed while bark, buds, and nuts remain where they are.", meaning: "Practice leaving room for a living place to continue beyond your visit. Attention can be a form of participation that asks very little of the tree.", question: "What would careful attention look like here?" },
    ],
    practiceTitle: "Give the next layer time.",
    practiceIntroduction: "An original five-minute practice connecting a close look at bark with patience for an ongoing effort.",
    practice: [
      { title: "Choose a clear viewpoint", text: "Find stable, permitted ground away from falling nuts or damaged branches. Sit or stand with support and keep your gaze at a comfortable height." },
      { title: "Look along the layers", text: "Notice a bark strip, a furrow, or a line of buds. Follow its edge with your eyes. Keep bark attached and leave nuts for the surrounding life." },
      { title: "Name the current stage", text: "Bring one ongoing effort to mind. Describe where it stands in a plain sentence. Let that description be accurate without asking it to be impressive." },
      { title: "Choose patient care", text: "Name one small action that would help the effort develop. Give it a realistic place in your day, then return to the tree for a final look." },
    ],
    reflection: "What would patient care change about your next step?",
    principles: "Perseverance, acceptance, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/carya-ovata/",
  },
  {
    slug: "silver-maple", name: "Silver Maple", species: "Silver maple", scientificName: "Acer saccharinum",
    ...fourTreeImages["silver-maple"],
    themes: ["Perspective", "Adaptability", "Balance"],
    invitation: "Watch a familiar surface change. Allow another angle to add to what you know.",
    introduction: "A moving leaf may offer two very different views in a moment. Begin with the light that reaches you, allowing the scene to change without having to follow every movement.",
    identity: [
      { title: "Leaves", text: "Opposite leaves have five deeply cut lobes and pale, silvery undersides. Compare several leaves and twigs; red maple has shallower cuts, and hybrids can complicate identification." },
      { title: "Bark and seeds", text: "Older bark forms loose-looking strips. Paired winged fruits, called samaras, develop after early flowers. Observe fallen fruits in place when branches are out of reach." },
      { title: "Place", text: "Native to eastern and central North America, silver maple often grows near waterways and in floodplains. It is also planted as a shade tree." },
    ],
    seasons: "Flowers can appear in late winter or early spring before leaves. Winged fruits follow in spring. Summer breezes may reveal pale leaf undersides; autumn color is often yellow. Winter exposes the branching outline. Timing varies with location.",
    energies: [
      { title: "Perspective", observation: "A turning leaf can show a darker upper surface and a paler underside.", meaning: "Let a changing view remind you that an initial impression may be incomplete. One additional angle can improve your understanding.", question: "What might another viewpoint add?" },
      { title: "Adaptability", observation: "Leaves change position while the branch remains part of the same tree.", meaning: "Use the movement as a prompt to adjust a method while remembering your purpose. A small revision can be enough.", question: "Which part of your approach could be adjusted?" },
      { title: "Balance", observation: "Some parts of the scene move while others appear still.", meaning: "Notice both without chasing every change. Choose where your attention rests, and allow the rest of the scene to remain present.", question: "What can you attend to without trying to manage everything?" },
    ],
    practiceTitle: "Let another angle in.",
    practiceIntroduction: "An original five-minute practice in perspective, using a changing view as a starting point for reflection.",
    practice: [
      { title: "Settle in a suitable place", text: "Choose calm weather and stable, permitted ground away from damaged or overhanging limbs. Use a comfortable seat or stance; a distant view is welcome." },
      { title: "Watch one small area", text: "Notice a leaf cluster as light or breeze changes it. In still weather or winter, compare a lit and shaded part of a branch without moving from your supported position." },
      { title: "Hold two descriptions", text: "Name two things you can see that belong to the same scene. Give both room in your description. Let your breath continue at its ordinary pace." },
      { title: "Make room for a revision", text: "Think of a situation you have seen from one angle. Name a useful question you could ask or one detail you could check. Finish with that modest intention." },
    ],
    reflection: "What did a second angle add to your first impression?",
    principles: "Adaptability, balance and optimization, and presence",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/acer-saccharinum/",
  },
  {
    slug: "black-cherry", name: "Black Cherry", species: "Black cherry", scientificName: "Prunus serotina",
    ...fourTreeImages["black-cherry"],
    themes: ["Relationship", "Generosity", "Listening"],
    invitation: "Notice the life around one tree. Let your attention make room for another presence.",
    introduction: "Begin with the tree, then allow a little of its surroundings into the encounter. A sound, a shadow, or an empty branch can be enough. Wildlife does not need to appear for this practice to matter.",
    identity: [
      { title: "Leaves and bark", text: "Alternate leaves have finely toothed edges. Young bark is relatively smooth with visible lenticels; older bark develops dark, flaky plates. Check several features before naming the tree." },
      { title: "Flowers and fruit", text: "Small white flowers appear in elongated clusters. Fruits change from red toward dark purple or black as they ripen. Observe without tasting, chewing, or collecting any part of the tree." },
      { title: "Place and wildlife", text: "A member of the rose family widespread in eastern North America, black cherry occurs in woods and open edges. Flowers serve pollinators and fruits feed birds and other wildlife." },
    ],
    seasons: "Look for flower clusters with spring foliage, followed by developing summer fruits. Autumn leaves can turn yellow or orange. Winter reveals buds, twigs, and bark patterns. Birds and insects may visit at different times; observe without disturbing them.",
    energies: [
      { title: "Relationship", observation: "The tree shares a scene with neighboring plants, passing sounds, and changing light.", meaning: "Let the wider view prompt awareness of the relationships surrounding your own work and daily life.", question: "Who or what helps make your day possible?" },
      { title: "Generosity", observation: "A flowering or fruiting tree may attract other living things.", meaning: "Use that possibility as a prompt to consider something useful you can offer. Keep the gesture small enough to carry out with care.", question: "What could you share without overextending yourself?" },
      { title: "Listening", observation: "Some nearby activity becomes noticeable when you stop moving or speaking.", meaning: "Practice leaving a little space before responding. Listening can also mean attending to visible movement when sound is unavailable.", question: "What becomes noticeable when you leave a pause?" },
    ],
    practiceTitle: "Leave room for another presence.",
    practiceIntroduction: "An original five-minute practice in listening and relationship, with visual observation available throughout.",
    practice: [
      { title: "Arrive without disturbing", text: "Choose a comfortable, supported position on permitted ground. Keep distance from nests and visiting wildlife. Leave leaves, bark, and fruit untouched." },
      { title: "Begin with one detail", text: "Look at a bark pattern or branch junction. Describe it quietly to yourself. Let your breathing remain natural." },
      { title: "Include the surroundings", text: "Allow one nearby sound or visible movement into your attention. If nothing moves, notice the space between branches. There is no need to attract wildlife or wait for an event." },
      { title: "Carry the pause with you", text: "Choose one conversation or interaction where you could leave more room to listen. Take one final look, then continue at your own pace." },
    ],
    reflection: "What did you notice when the tree became part of a wider scene?",
    principles: "Presence, acceptance, and adaptability",
    sourceUrl: "https://plants.ces.ncsu.edu/plants/prunus-serotina/",
  },
];
