// Contemporary Tree Yoga School practice; research is linked on /tree-hugging.
export const treeHuggingPractice = {
  title: "Hug a tree. Come back to yourself.",
  reflection: "What changes when you give your attention to a living thing?",
  steps: [
    { title: "Meet the tree", text: "Choose a tree you may approach on stable, permitted ground. Look at its trunk and canopy. Notice its shape, a pattern in the bark, and what is living around it. Let this particular tree become the center of your attention." },
    { title: "Find your embrace", text: "Stand comfortably and rest your hands or arms lightly against the trunk, only if touch feels welcome to you and is allowed here. Keep your own balance; the tree need not bear your weight. Your arms do not have to meet. One palm, a seated view, or simply being nearby is enough." },
    { title: "Let the senses lead", text: "Notice texture, temperature, light, and sound. Keep your face clear of the bark and your breathing natural. Let your shoulders soften if comfortable. Stay aware of your surroundings, with eyes open if that feels better." },
    { title: "Stay, and return", text: "Let this one tree be your point of attention. When thoughts wander, come back to a texture, a sound, or the movement of your breath. Stay for a few breaths or a few minutes. Change position or step away whenever you wish." },
    { title: "Release with care", text: "Ease your hands away. Notice your body and the space around you before moving. Offer a quiet thank-you if that feels right. Leave bark, leaves, roots, and the life around the tree undisturbed." },
  ],
} as const;

export const treeHuggingResearch = [
  { id: "forest", number: 1, year: "2010", title: "Forest environments and relaxation", citation: "Park et al. · Environmental Health and Preventive Medicine", url: "https://doi.org/10.1007/s12199-009-0086-9", finding: "Field experiments across 24 Japanese forests compared walking and viewing in forest and city settings. The 280 young participants showed lower cortisol, pulse rate, and blood pressure, and differences in autonomic activity, in forest settings.", limit: "These were short-term responses in a narrow age group, not evidence that an individual hug treats stress or a health condition." },
  { id: "attention", number: 2, year: "2015", title: "Nature walks and repetitive thought", citation: "Bratman et al. · Proceedings of the National Academy of Sciences", url: "https://doi.org/10.1073/pnas.1510459112", finding: "In a study of 38 healthy urban residents, the nature-walk group reported less rumination after a 90-minute walk and showed a change in a brain region associated with rumination.", limit: "A small walking study cannot tell us whether a five-minute tree embrace produces the same effect." },
  { id: "touch", number: 3, year: "2017", title: "Wood as a tactile experience", citation: "Ikei, Song & Miyazaki · International Journal of Environmental Research and Public Health", url: "https://pubmed.ncbi.nlm.nih.gov/28718814/", finding: "A laboratory experiment compared palm contact with uncoated white oak, marble, tile, and steel. Touching wood produced physiological responses consistent with relaxation relative to some other materials.", limit: "The experiment used wood surfaces, not living bark or a tree hug. It offers a possible connection, not proof of the benefits of this practice." },
  { id: "care", number: 4, year: "2020", title: "Feeling connected and caring for nature", citation: "Whitburn, Linklater & Abrahamse · Conservation Biology (online 2019)", url: "https://pubmed.ncbi.nlm.nih.gov/31251416/", finding: "A meta-analysis of 37 samples, including 13,237 people, found that stronger connection to nature was associated with more reported pro-environmental behavior.", limit: "Association does not establish that hugging trees causes conservation behavior. Our invitation is to turn attention into care." },
  { id: "embrace", number: 5, year: "2025", title: "Tree embracing within forest therapy", citation: "Giant Panda National Park study · Frontiers in Psychology", url: "https://doi.org/10.3389/fpsyg.2025.1630999", finding: "An exploratory forest-therapy study with 32 healthcare workers included embracing trees among several sensory and contemplative activities. Participants rated tree embracing favorably in the forest setting.", limit: "This small, multi-activity program did not isolate a hug as a treatment or establish lasting effects." },
] as const;
